<!DOCTYPE html>
<html lang="en"><head>
<link href="../assets/dhbw_logo.svg" rel="icon" type="image/svg+xml">
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-contrib/livefigures-0.8.0/livefigures.css" rel="stylesheet"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.10.18">

  <meta name="author" content="Prof.&nbsp;Dr.-Ing. Daniel Klünder">
  <title>Echtzeitsysteme – 06 · Multicore-Echtzeit</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: 1.5em;}
    div.column{flex: auto;}
    @media screen {
    div.columns{gap: min(4vw, 1.5em);}
    div.column{overflow-x: auto;}
    }
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="../site_libs/revealjs/dist/theme/quarto-f355cf95444bdbe7a358cd689c441e6f.css">
  <link href="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <script src="../site_libs/quarto-diagram/mermaid.min.js"></script>
  <script src="../site_libs/quarto-diagram/mermaid-init.js"></script>
  <link href="../site_libs/quarto-diagram/mermaid.css" rel="stylesheet">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&amp;display=swap" rel="stylesheet">
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">06 · Multicore-Echtzeit</h1>
  <p class="subtitle">AMP, STM32H755 und Shared Memory · EZS · DHBW Stuttgart</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Prof.&nbsp;Dr.-Ing. Daniel Klünder
</div>
</div>
</div>

</section>
<section id="willkommen-in-der-multicore-königsklasse" class="slide level2">
<h2>Willkommen in der Multicore-Königsklasse!</h2>
<ul>
<li>Herzlich willkommen zum 6. Termin unserer Vorlesung</li>
<li>Die letzten 5 Wochen: Single-Core-Echtzeit (Scheduling, IPC, Interrupts)</li>
<li>Heute heben wir die Komplexität auf das nächste Level: Multicore-Systeme</li>
<li>Zwei unterschiedliche Prozessorkerne in einem Chip</li>
<li>Praxis am Nachmittag: zweites „Gehirn“ des STM32H755 aufwecken</li>
</ul>
<aside class="notes">
<p>Guten Morgen und herzlich willkommen in der Königsklasse der Embedded-Programmierung! In den letzten fünf Wochen: Task-Scheduling, Queues, Hardware-Interrupts über Semaphoren — alles auf einem Prozessorkern. Heute: Multicore-Architekturen, warum Ihr PC anders tickt als ein Steuergerät, und wie wir auf dem STM32H755 zwei Kerne parallel und sicher betreiben.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="agenda-für-heute" class="slide level2">
<h2>Agenda für heute</h2>
<ol type="1">
<li>Recap: Die Grenzen der Single-Core-Architektur</li>
<li>Symmetrisches vs.&nbsp;Asymmetrisches Multiprocessing (SMP vs.&nbsp;AMP)</li>
<li>Hardware Deep-Dive: Dual-Core-Architektur des STM32H755</li>
<li>Boot-Prozess und Toolchain-Setup für zwei Kerne</li>
<li>Die Speicherarchitektur (RAM-Domänen)</li>
<li><em>[Nach der Pause]</em> Shared Memory und Cache-Kohärenz</li>
<li>Ausblick Labor: Ping-Pong-Datenaustausch</li>
</ol>
<aside class="notes">
<p>Motivation für mehrere Kerne, dann SMP vs.&nbsp;AMP. Anschließend den STM32H755 zerlegen: M7 und M4, Boot und Speicheraufteilung. Nach der Pause: Cache-Kohärenz bei geteiltem Speicher. Am Nachmittag kommunizieren beide Kerne live.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="recap-die-grenzen-des-single-core" class="slide level2">
<h2>Recap: Die Grenzen des Single-Core</h2>
<ul>
<li>Erinnern wir uns an die Schedulability-Tests (Termin 2)</li>
<li>EDF-Schranke: <span class="math inline">\(\sum \frac{C_i}{T_i} \le 1\)</span> (<span class="math inline">\(100\%\)</span> Auslastung)</li>
<li>Bei <span class="math inline">\(100\%\)</span> CPU-Nutzung ist physikalisch Schluss</li>
<li>Das Problem der Industrie:
<ul>
<li>Steuergeräte sollen immer mehr können (KI, Ethernet, GUI)</li>
<li>Gleichzeitig harte Timing-Regelkreise (<span class="math inline">\(100\,\text{µs}\)</span> Raster)</li>
</ul></li>
<li>Wie bekommen wir mehr Rechenleistung in das System?</li>
</ul>
<aside class="notes">
<p>Woche 2: EDF kann die CPU zu 100% auslasten — mathematisches Limit. Ein modernes Automotive-Steuergerät soll Kamerabilder mit KI auswerten, Touch-Display bespielen und den Elektromotor mit Mikrosekunden-Präzision ansteuern. Ein einzelner Kern ist überfordert. Wir brauchen mehr Rechenleistung.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="erhöhung-der-taktfrequenz" class="slide level2">
<h2>Erhöhung der Taktfrequenz?</h2>
<ul>
<li>Warum takten wir den Cortex-M4 nicht mit <span class="math inline">\(5\,\mathrm{GHz}\)</span> statt <span class="math inline">\(240\,\mathrm{MHz}\)</span>?</li>
<li>Die Power Wall (Leistungsmauer):
<ul>
<li>Höherer Takt → höhere Spannung → exponentiell mehr Abwärme</li>
<li>Embedded Systems oft ohne Lüfter (z. B. vergossenes Motorsteuergerät)</li>
</ul></li>
<li>Die Memory Wall (Speichermauer):
<ul>
<li>RAM-Zugriffszeiten skalieren nicht mit CPU-Takten</li>
<li>Die CPU wartet auf Daten (Pipeline Stalls)</li>
</ul></li>
</ul>
<aside class="notes">
<p>Intuitiv: Takt erhöhen. Physik: Power Wall — 5 GHz erzeugen massive Abwärme. Im PC: Kühler und Lüfter. Im Auto: oft am Getriebeblock, wasserdicht vergossen, 100 Grad Umgebungstemperatur ohne Lüfter. Memory Wall: selbst bei 5 GHz intern liefert der Arbeitsspeicher zu langsam — die CPU verbrennt Zeit mit Warten.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="der-ausweg-multicore-architekturen" class="slide level2">
<h2>Der Ausweg: Multicore-Architekturen</h2>
<ul>
<li>Lösung: lieber mehrere langsame, effiziente Kerne als ein extrem heißer, schneller Kern</li>
<li>Beispiele aus der Industrie:
<ul>
<li>Automotive Domain Controller: viele kleine Steuergeräte in einem Multicore-Chip</li>
<li>Industrie 4.0 (Edge Computing): ein Core steuert die Maschine (harte Echtzeit), ein anderer funkt in die Cloud (weiche Echtzeit)</li>
</ul></li>
<li>Multicore in der Echtzeit ist fundamental anders als in Ihrem Laptop</li>
</ul>
<aside class="notes">
<p>Die Lösung von Intel/AMD für den PC ist in der MCU-Welt angekommen: Multicore. Automotive: Domain Controller statt vieler Einzelprozessoren. Industrie 4.0: harte Echtzeit auf einem Kern, MQTT/OPC-UA auf dem anderen. Aber: Echtzeit-Multicore tickt völlig anders als der i7 in Ihrem Laptop.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="multiprocessing-architekturen" class="slide level2">
<h2>Multiprocessing-Architekturen</h2>
<p>Zwei grundlegende Konzepte:</p>
<ol type="1">
<li>SMP (Symmetric Multiprocessing)</li>
<li>AMP (Asymmetric Multiprocessing)</li>
</ol>
<p>Beide haben unterschiedliche Einsatzgebiete.</p>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">graph TD
    MC[Multicore] --&gt; SMP[SMP Symmetrisch]
    MC --&gt; AMP[AMP Asymmetrisch]
    style MC fill:#FFFFFF,stroke:#1D1D1F,stroke-width:1px !important
    style SMP fill:#FFFFFF,stroke:#E2001A,stroke-width:2px !important
    style AMP fill:#FFFFFF,stroke:#E2001A,stroke-width:2px !important
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<aside class="notes">
<p>Es gibt nicht „die eine“ Multicore-Architektur. Zwei Familien: SMP und AMP. Beide lösen Rechenlast, aber auf unterschiedlichen Wegen. Für Ihre Karriere: Unterschied kennen und wissen, warum AMP in der Echtzeit oft bevorzugt wird.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="symmetrisches-multiprocessing-smp" class="slide level2">
<h2>Symmetrisches Multiprocessing (SMP)</h2>
<ul>
<li>Die PC- und Smartphone-Welt (Windows, Linux, Android, iOS)</li>
<li>Architekturmerkmale:
<ul>
<li>Alle Kerne physisch identisch (z. B. 4× Cortex-A53)</li>
<li>Gemeinsamer physikalischer Speicher (RAM)</li>
<li>Genau ein Betriebssystem über alle Kerne</li>
<li>Das OS orchestriert alle Kerne zentral</li>
</ul></li>
</ul>
<aside class="notes">
<p>SMP kennen Sie aus Alltag: Handy und Laptop. „Symmetrisch“: identische Kerne, gleicher Befehlssatz, gleicher Takt, gemeinsamer RAM. Darüber liegt ein einziges OS (Windows, Linux-Kernel). Das OS sieht alle Kerne und verteilt die Arbeit.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="wie-funktioniert-ein-smp-scheduler" class="slide level2">
<h2>Wie funktioniert ein SMP-Scheduler?</h2>
<ul>
<li>Das OS hat eine Ready-Warteschlange für Tasks</li>
<li>Load-Balancing: Tasks dynamisch auf den Kern mit wenig Last</li>
<li>Task-Migration: Millisekunde 1 auf Core 0, Millisekunde 2 auf Core 1</li>
</ul>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">graph TD
    OS[Single OS Linux / Windows] --&gt; TQ[Task-Queue]
    TQ --&gt; C0[Core 0 Task A]
    TQ --&gt; C1[Core 1 Task B]
    TQ --&gt; C2[Core 2 Task C]
    C2 -.-&gt;|Migration| C0
    style OS fill:#FFFFFF,stroke:#1D1D1F,stroke-width:1px !important
    style TQ fill:#F5F5F7,stroke:#E2001A,stroke-width:2px !important
    style C0 fill:#FFFFFF,stroke:#E2001A,stroke-width:2px !important
    style C1 fill:#FFFFFF,stroke:#E2001A,stroke-width:2px !important
    style C2 fill:#FFFFFF,stroke:#E2001A,stroke-width:2px !important
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<aside class="notes">
<p>Der SMP-Scheduler betreibt Load-Balancing. Word, Excel, Browser: OS weist Threads freien Kernen zu. Task-Migration: Thread startet auf Core 0, wird pausiert, läuft später auf Core 1 weiter — Register wandern mit. Fantastische Gesamtauslastung.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="warum-smp-für-harte-echtzeit-oft-scheitert" class="slide level2">
<h2>Warum SMP für harte Echtzeit oft scheitert</h2>
<ul>
<li>SMP ist genial für Durchsatz, aber für <strong>harte</strong> Echtzeit oft problematisch</li>
<li>Latenz-Probleme:
<ul>
<li>Task-Migration kostet Zeit (Register von Kern zu Kern)</li>
<li>Cache-Thrashing: L1-Cache des Zielkerns ist leer → Cache-Misses</li>
<li>Contention: mehrere Kerne auf demselben RAM-Bus → Mikro-Staus</li>
</ul></li>
<li>Ergebnis: WCET wird schwerer vorherzusagen (oft unpraktisch für harte Deadlines)</li>
</ul>
<aside class="notes">
<p>Warum selten Airbag-Steuerung mit SMP? Determinismus leidet. Migration: Register kopieren und L1-Cache leer → Jitter. Bus-Staus bei parallelem RAM-Zugriff. Die WCET für den Schedulability-Test wird schwer beherrschbar.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="asymmetrisches-multiprocessing-amp" class="slide level2">
<h2>Asymmetrisches Multiprocessing (AMP)</h2>
<ul>
<li>Die Embedded-Welt (Steuergeräte, Motor-Regler)</li>
<li>Architekturmerkmale:
<ul>
<li>Kerne oft unterschiedlich (z. B. Cortex-M7 und Cortex-M4)</li>
<li>System strikt partitioniert</li>
<li>Jeder Kern führt eigenes Programm / OS aus</li>
<li>Kerne wissen beim Start oft nichts voneinander</li>
</ul></li>
</ul>
<aside class="notes">
<p>Daher AMP in der Echtzeit. Asymmetrisch: oft ungleiche Kerntypen — wuchtiger Kern für Rechnen, präziser Kern für Steuerung. Kein Über-Betriebssystem: zwei unabhängige Programme. Core A und Core B booten getrennt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="software-aufteilung-in-amp" class="slide level2">
<h2>Software-Aufteilung in AMP</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p>Core 1 (z. B. Cortex-M7)</p>
<ul>
<li>OS: Embedded Linux oder Bare-Metal</li>
<li>Job: GUI, Netzwerk (TCP/IP), ML</li>
<li>Fokus: Durchsatz (weiche Echtzeit)</li>
</ul>
</div><div class="column" style="width:50%;">
<p>Core 2 (z. B. Cortex-M4)</p>
<ul>
<li>OS: FreeRTOS oder AUTOSAR</li>
<li>Job: PWM, Encoder, PID-Regler</li>
<li>Fokus: Determinismus (harte Echtzeit)</li>
</ul>
</div></div>
<ul>
<li><span class="math inline">\(100\%\)</span> CPU-Load auf Core 1 hat keine Auswirkung auf das Timing von Core 2</li>
</ul>
<aside class="notes">
<p>Bestes aus beiden Welten: rechenstarker Kern mit Linux/Netzwerk (Timing darf schwanken), kleiner Kern mit FreeRTOS und Motor-PWM. Isolation fast perfekt: hängt Linux bei 100% Auslastung, tuckert der FreeRTOS-Regler jitterfrei weiter — Safety per Hardware-Design.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="wie-kommunizieren-amp-kerne" class="slide level2">
<h2>Wie kommunizieren AMP-Kerne?</h2>
<ul>
<li>Kein gemeinsames OS → keine normale FreeRTOS-Queue von Core 1 nach Core 2</li>
<li>Kommunikation über Hardware-Mechanismen:
<ul>
<li>Message Buffers (Hardware-Mailboxes): Schreiben löst Interrupt am anderen Kern aus</li>
<li>Hardware-FIFOs: echte Puffer zwischen den Kernen</li>
<li>Shared Memory (SRAM): vereinbarter RAM-Bereich mit physischem Zugriff beider Kerne</li>
</ul></li>
<li>Heute: Shared Memory — flexibel, aber gefährlich</li>
</ul>
<aside class="notes">
<p>Wie reden die Kerne? <code>osMessageQueuePut</code> geht nicht — FreeRTOS auf Core 2 kennt die Datenstrukturen von Bare-Metal auf Core 1 nicht. Hardware hilft: Queues oder Shared Memory. Beide Kerne greifen auf denselben RAM-Block zu. Schnell, aber tückisch bei der Datenintegrität.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="zusammenfassung-block-1" class="slide level2">
<h2>Zusammenfassung Block 1</h2>
<table class="caption-top">
<colgroup>
<col style="width: 25%">
<col style="width: 36%">
<col style="width: 38%">
</colgroup>
<thead>
<tr class="header">
<th>Eigenschaft</th>
<th>SMP (Symmetrisch)</th>
<th>AMP (Asymmetrisch)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Kerne</td>
<td>Identisch</td>
<td>Oft heterogen</td>
</tr>
<tr class="even">
<td>Betriebssystem</td>
<td>Ein gemeinsames OS</td>
<td>Getrennte Programme / OS</td>
</tr>
<tr class="odd">
<td>Lastverteilung</td>
<td>Dynamisch durch Scheduler</td>
<td>Statisch durch Programmierer</td>
</tr>
<tr class="even">
<td>Determinismus</td>
<td>Oft schwierig (Migration, Cache-Misses)</td>
<td>Typischerweise besser isolierbar</td>
</tr>
<tr class="odd">
<td>Beispiel</td>
<td>Laptop, Raspberry Pi</td>
<td>STM32H755, NXP i.MX RT</td>
</tr>
</tbody>
</table>
<aside class="notes">
<p>SMP: identische Kerne, ein OS, Meister des Durchsatzes. AMP: oft ungleiche Kerne, strikte Isolation, Meister des Determinismus. Wir bauen fast ausschließlich AMP-Systeme. Als Nächstes: der STM32H755 im Detail.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="hardware-deep-dive-der-stm32h755" class="slide level2">
<h2>Hardware Deep-Dive: Der STM32H755</h2>
<ul>
<li>Ein Silizium-Plättchen (Die), zwei getrennte Prozessorkerne</li>
</ul>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">graph TD
    CHIP[STM32H755 Chip]
    CHIP --&gt; M7[Cortex-M7 Spec max 480 MHz]
    CHIP --&gt; M4[Cortex-M4 Spec max 240 MHz]
    style CHIP fill:#FFFFFF,stroke:#1D1D1F,stroke-width:1px !important
    style M7 fill:#F5F5F7,stroke:#E2001A,stroke-width:2px !important
    style M4 fill:#F5F5F7,stroke:#E2001A,stroke-width:2px !important
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<ul>
<li>Trotzdem teilen sie sich Pins, Taktquellen und Speicher</li>
<li>Wie organisiert STMicroelectronics dieses Chaos?</li>
</ul>
<aside class="notes">
<p>Der STM32H755 ist ein Flaggschiff der AMP-Architektur. Ein Gehäuse, zwei Herzen: Cortex-M7 und Cortex-M4. Logisch getrennt, physisch im selben Package: Strom, Clocks, Pins teilen. Core 1 darf Pin A5 nicht High setzen, während Core 2 ihn Low zieht.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="der-cortex-m7-das-muskelpaket" class="slide level2">
<h2>Der Cortex-M7 (Das Muskelpaket)</h2>
<ul>
<li>Unser Core 1 (Master)</li>
<li>Specs: bis <span class="math inline">\(480\,\mathrm{MHz}\)</span>, 6-stufige superskalare Pipeline</li>
<li>Superskalar: zwei Instruktionen in einem Taktzyklus möglich</li>
<li>Caches:
<ul>
<li>L1 Data Cache (<span class="math inline">\(16\,\mathrm{KB}\)</span>)</li>
<li>L1 Instruction Cache (<span class="math inline">\(16\,\mathrm{KB}\)</span>)</li>
</ul></li>
<li>FPU: Double-Precision (64-Bit)</li>
<li>Ziel: Rechenleistung, schnelle Netzwerk-Verarbeitung</li>
</ul>
<aside class="notes">
<p>Core 1, der Cortex-M7: Muskelpaket bis 480 MHz, superskalar mit parallelen Rechenwerken. L1-Caches für Daten und Code, weil RAM für 480 MHz zu langsam ist. 64-Bit-FPU. Gebaut für Filter, Ethernet und Touch-Displays.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="der-cortex-m4-das-präzisionswerkzeug" class="slide level2">
<h2>Der Cortex-M4 (Das Präzisionswerkzeug)</h2>
<ul>
<li>Unser Core 2</li>
<li>Specs: bis <span class="math inline">\(240\,\mathrm{MHz}\)</span>, 3-stufige Pipeline</li>
<li>Wichtigster Unterschied: keine Caches!</li>
<li>Ausführungszeit eines Assembler-Befehls ist absolut deterministisch</li>
<li>FPU: Single-Precision (32-Bit)</li>
<li>Ziel: harte Echtzeit-Regelung, enge Anbindung an Timer und ADC</li>
<li>Hier lassen wir FreeRTOS laufen</li>
</ul>
<aside class="notes">
<p>Der Cortex-M4: halb so schnell, simplere Pipeline. Entscheidend: keine Caches. Jeder Speicherzugriff dauert immer gleich viele Takte — Timing auf die Nanosekunde vorherberechenbar. Skalpell neben dem Vorschlaghammer. Ideal für Motoren und Leistungselektronik. FreeRTOS läuft heute Nachmittag exklusiv auf dem M4.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="die-bus-matrix-ahb-axi" class="slide level2">
<h2>Die Bus-Matrix (AHB / AXI)</h2>
<ul>
<li>Kerne, Speicher und Peripherie: keine einzelne Leitung, sondern eine Matrix</li>
<li>AXI-Bus-Matrix: Netzwerk aus Schaltern</li>
<li>Vorteil: M7 liest Flash, während M4 eine GPIO-LED schaltet — ohne Blockade</li>
<li>Blockaden nur, wenn beide Cores im selben Takt dasselbe Ziel treffen</li>
</ul>
<aside class="notes">
<p>Früher: ein Bus, eine Hauptstraße. Der STM32H7 nutzt eine AXI-Bus-Matrix — Autobahnkreuze und Brücken. M7 auf Flash und M4 auf GPIO kreuzen sich nicht. Stau nur bei gleichzeitigem Zugriff auf dasselbe Modul; die Matrix regelt Vorfahrt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="die-3-power-domänen-d1-d2-d3" class="slide level2">
<h2>Die 3 Power-Domänen (D1, D2, D3)</h2>
<ul>
<li>D1 (High-Performance Domain):
<ul>
<li>Cortex-M7, AXI-SRAM, High-Speed USB, Ethernet</li>
</ul></li>
<li>D2 (Real-Time Domain):
<ul>
<li>Cortex-M4, SRAM 1/2/3, Timer, ADCs, UARTs</li>
</ul></li>
<li>D3 (Low-Power Domain):
<ul>
<li>RTC, SRAM 4</li>
<li>Läuft oft weiter, wenn D1 und D2 schlafen</li>
</ul></li>
</ul>
<aside class="notes">
<p>Drei Kontinente: D1 (Partyzone mit M7 und Gigabit), D2 (Echtzeit-Zone mit M4 und Timern), D3 (Low-Power). Im Batteriebetrieb können D1 und D2 abgeschaltet werden — D3 hält Uhr und SRAM4 mit Mikroampere am Leben.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="taktversorgung-rcc" class="slide level2">
<h2>Taktversorgung (RCC)</h2>
<ul>
<li>Specs vs.&nbsp;Board-Setup (kanonisch für diese Vorlesung):</li>
</ul>
<table class="caption-top">
<thead>
<tr class="header">
<th>Kern</th>
<th>Spec-Maximum</th>
<th>Typisches Nucleo-Setup</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Cortex-M7</td>
<td>bis <span class="math inline">\(480\,\mathrm{MHz}\)</span></td>
<td><span class="math inline">\(400\,\mathrm{MHz}\)</span></td>
</tr>
<tr class="even">
<td>Cortex-M4</td>
<td>bis <span class="math inline">\(240\,\mathrm{MHz}\)</span></td>
<td><span class="math inline">\(200\,\mathrm{MHz}\)</span></td>
</tr>
</tbody>
</table>
<ul>
<li>Beide Kerne haben eigene Phasenregelkreise (PLLs)</li>
<li>Achtung im CubeMX Configurator:
<ul>
<li>Änderungen am System Clock beeinflussen meist beide Kerne</li>
<li>Stoppt Core 1 die PLL, crasht Core 2</li>
</ul></li>
</ul>
<aside class="notes">
<p>Ähnliche Teilung bei RCC: eigene Teiler und PLLs. Specs nennen Maxima (480/240); im Labor und in Timing-Beispielen (Cache, Trace) rechnen wir mit dem typischen Nucleo-Setup 400/200 MHz. Falle: der externe Quarz ist gemeinsam. Schaltet M7 den Hauptoszillator ab, bleibt dem M4 das Herz stehen — einer muss Boss bleiben.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="der-boot-prozess-wer-weckt-wen" class="slide level2">
<h2>Der Boot-Prozess: Wer weckt wen?</h2>
<ul>
<li>Beim Einschalten starten nicht beide Kerne</li>
<li>Cortex-M7 ist der Master und bootet zuerst</li>
<li>Cortex-M4 ist der Slave und bleibt im Reset (Hold)</li>
<li>Aufgabe des M7:
<ul>
<li>System-Clock hochfahren</li>
<li>RAM und Peripherie stabilisieren</li>
<li>Hardware-Schalter umlegen, der den M4 entfesselt</li>
</ul></li>
</ul>
<aside class="notes">
<p>Häufige Anfängerfrage: Wer startet zuerst? Nur der M7. Der M4 bleibt im Reset. M7 konfiguriert Taktbaum und Bus-Matrix, legt dann den Schalter um — M4 springt in seine eigene <code>main()</code>.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="hardware-register-den-m4-wecken" class="slide level2">
<h2>Hardware-Register: Den M4 wecken</h2>
<ul>
<li>Schalter im Power-Management-Register (PWR)</li>
<li>In der <code>main.c</code> des M7:</li>
</ul>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode numberSource c number-lines code-with-copy"><code class="sourceCode c"><span id="cb1-1"><a aria-label="1"></a><span class="co">// Weckt den Cortex-M4 auf</span></span>
<span id="cb1-2"><a aria-label="2"></a>HAL_PWREx_ReleaseCore<span class="op">(</span>PWR_CORE_CPU2<span class="op">);</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<ul>
<li>Ohne diese Zeile läuft FreeRTOS auf dem M4 nie</li>
</ul>
<aside class="notes">
<p>Diesen Schalter betätigen Sie heute Nachmittag selbst. In der M7-<code>main.c</code>: <code>HAL_PWREx_ReleaseCore(PWR_CORE_CPU2)</code>. Blinken die M4-LEDs nicht: zuerst diese Zeile prüfen.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="pin-zuweisung-im-dual-core" class="slide level2">
<h2>Pin-Zuweisung im Dual-Core</h2>
<ul>
<li>Dem Chip ist egal, wer einen GPIO-Pin schaltet</li>
<li>Gefahr: M7 und M4 konfigurieren denselben Pin → Register-Konflikte</li>
<li>Im CubeMX Configurator:
<ul>
<li>Pin Context Assignment → ARM Cortex-M7 oder ARM Cortex-M4</li>
<li>Codegenerator schreibt <code>HAL_GPIO_Init</code> nur in die <code>main.c</code> des zugewiesenen Cores</li>
</ul></li>
</ul>
<aside class="notes">
<p>Beide können auf GPIO schreiben. M7 als Ausgang und M4 als Eingang am selben Pin kracht. In CubeIDE: Pin Context Assignment. Der Generator schreibt die Init nur in den Ordner des zugewiesenen Kerns — saubere Architektur.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="toolchain-und-projektstruktur" class="slide level2">
<h2>Toolchain und Projektstruktur</h2>
<ul>
<li>Dual-Core-Projekt in CubeIDE: drei Ordner
<ul>
<li><code>Project_CM7</code>: eigene <code>main.c</code>, eigene Linker-Skripte</li>
<li><code>Project_CM4</code>: isolierte Code-Basis für den M4</li>
<li><code>Project_Common</code>: gemeinsame Dateien (z. B. HAL-Treiber)</li>
</ul></li>
<li>Beim Kompilieren entstehen zwei unabhängige <code>.elf</code> / <code>.bin</code>-Dateien</li>
</ul>
<aside class="notes">
<p>Drei Ordner statt einem: CM7 und CM4 mit eigener <code>main.c</code>, Interrupt-Tabellen und Linker-Skripten — zwei C-Projekte. Common nur für gemeinsame Treiber. GCC wirft zwei Firmware-Dateien aus: eine für Master, eine für Slave.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="debugging-im-amp-system" class="slide level2">
<h2>Debugging im AMP-System</h2>
<ul>
<li>ST-Link unterstützt Multicore-Debugging</li>
<li>Debug startet zwei GDB-Instanzen parallel</li>
<li>Zwei Konsolen: Breakpoints von M7 und M4 umschalten</li>
<li>Flashen: Programm 1 in Bank 1, Programm 2 in Bank 2</li>
</ul>
<aside class="notes">
<p>Der ST-Link fragt beide Kerne per JTAG ab. Debug flasht beide Programme in getrennte Flash-Banken und startet zwei Debug-Server. Breakpoint im FreeRTOS des M4 setzen, dann in den M7-Tab wechseln und zuschauen, wie Bare-Metal weiterläuft.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="zusammenfassung-block-2" class="slide level2">
<h2>Zusammenfassung Block 2</h2>
<ul>
<li>STM32H755: High-Performance-Kern (M7 mit Cache) und Echtzeit-Kern (M4 ohne Cache)</li>
<li>Bus-Matrix routet Zugriffe kreuzungsfrei — außer bei exakt demselben Ziel</li>
<li>M7 bootet zuerst und weckt den M4</li>
<li>Zwei unabhängige Firmware-Dateien aus zwei Code-Ordnern</li>
</ul>
<aside class="notes">
<p>Zusammenfassung Hardware: schnelles und determiniertes Herz, Bus-Matrix gegen Staus, M7 als Boss, Software wie zwei separate Projekte. Fragen zur Hardware, bevor wir zum Speicher und zur Kommunikation gehen?</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="die-speicherarchitektur-ram" class="slide level2">
<h2>Die Speicherarchitektur (RAM)</h2>
<ul>
<li>Datenaustausch M7 → M4 braucht Shared Memory</li>
<li>Fast <span class="math inline">\(1\,\mathrm{MB}\)</span> RAM, aber aufgeteilt:
<ul>
<li>AXI-SRAM (D1): klebt am M7 — schnell für M7, langsam für M4</li>
<li>SRAM 1/2/3 (D2): klebt am M4 — schnell für M4, langsam für M7</li>
<li>SRAM 4 (D3): unabhängig, oft für Peripherie oder Standby</li>
</ul></li>
</ul>
<aside class="notes">
<p>AMP-Kerne reden über Shared Memory — aber es gibt nicht „den einen“ RAM. AXI-SRAM klebt am M7 (1 Takt für M7, teuer für M4 über die Bus-Matrix). SRAM 1–3 kleben beim M4 in D2.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="wo-legen-wir-den-shared-memory-an" class="slide level2">
<h2>Wo legen wir den Shared Memory an?</h2>
<ul>
<li>Neutraler Ort, gut erreichbar für beide Kerne</li>
<li>Best Practice: SRAM4 in der D3-Domäne</li>
<li>Basis-Adresse: <code>0x38000000</code> (Größe: <span class="math inline">\(64\,\mathrm{KB}\)</span>)</li>
<li>Ziel: C-Struct für Sensorwerte exakt an diese Adresse legen</li>
<li>Wie zwingen wir den Compiler dazu?</li>
</ul>
<aside class="notes">
<p>Treffpunkt oft SRAM4 in D3: 64 KB ab <code>0x38000000</code>. Ein C-Struct darf nicht irgendwo im AXI-SRAM landen — wir nageln es bytegenau auf diese Adresse.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="das-linker-script-.ld" class="slide level2">
<h2>Das Linker-Script (<code>.ld</code>)</h2>
<ul>
<li>GCC erzeugt Maschinencode; der Linker legt physikalische Adressen fest</li>
<li>Linker-Skripte beider Kerne anpassen:</li>
</ul>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode numberSource ld number-lines code-with-copy"><code class="sourceCode"><span id="cb2-1"><a aria-label="1"></a>/* Definition der Speicherbereiche */</span>
<span id="cb2-2"><a aria-label="2"></a>MEMORY</span>
<span id="cb2-3"><a aria-label="3"></a>{</span>
<span id="cb2-4"><a aria-label="4"></a>  FLASH (rx)      : ORIGIN = 0x08000000, LENGTH = 1024K</span>
<span id="cb2-5"><a aria-label="5"></a>  RAM_D1 (xrw)    : ORIGIN = 0x24000000, LENGTH = 512K</span>
<span id="cb2-6"><a aria-label="6"></a>  /* NEU: Shared Memory (CubeMX: oft RAM_D3) */</span>
<span id="cb2-7"><a aria-label="7"></a>  RAM_D3 (xrw)    : ORIGIN = 0x38000000, LENGTH = 64K</span>
<span id="cb2-8"><a aria-label="8"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<aside class="notes">
<p>Das Linker-Script ist das Fundament. In beiden <code>.ld</code>-Dateien einen MEMORY-Bereich <code>RAM_D3</code> (SRAM4) mit Adresse <code>0x38000000</code> und 64 KB deklarieren — beide Kerne kennen den Bereich.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="eine-eigene-sektion-anlegen" class="slide level2">
<h2>Eine eigene Sektion anlegen</h2>
<ul>
<li>Sektion (Container) im Shared-RAM anlegen:</li>
</ul>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="sourceCode numberSource ld number-lines code-with-copy"><code class="sourceCode"><span id="cb3-1"><a aria-label="1"></a>SECTIONS</span>
<span id="cb3-2"><a aria-label="2"></a>{</span>
<span id="cb3-3"><a aria-label="3"></a>  /* Sektion .shared_memory */</span>
<span id="cb3-4"><a aria-label="4"></a>  .shared_memory (NOLOAD) :</span>
<span id="cb3-5"><a aria-label="5"></a>  {</span>
<span id="cb3-6"><a aria-label="6"></a>    . = ALIGN(4);</span>
<span id="cb3-7"><a aria-label="7"></a>    *(.shared_memory) /* Variablen mit diesem Tag */</span>
<span id="cb3-8"><a aria-label="8"></a>  } &gt; RAM_D3</span>
<span id="cb3-9"><a aria-label="9"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<ul>
<li>Extrem wichtig: <code>(NOLOAD)</code>
<ul>
<li>Ohne NOLOAD füllt der Startup-Code den RAM mit Nullen</li>
<li>M7 schreibt, M4 bootet <span class="math inline">\(1\,\mathrm{ms}\)</span> später → Shared Memory wird genullt</li>
</ul></li>
</ul>
<aside class="notes">
<p>Sektion <code>.shared_memory</code> anlegen. Entscheidend: <code>NOLOAD</code>. Ohne NOLOAD initialisiert der Startup alle globalen Variablen mit 0. M7 schreibt Sensordaten, M4 bootet eine Millisekunde später und überschreibt den Shared Memory mit Nullen. NOLOAD verbietet dieses Nullen.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="zuweisung-im-c-code-gcc-attribute" class="slide level2">
<h2>Zuweisung im C-Code (GCC-Attribute)</h2>
<div class="columns">
<div class="column" style="width:50%;">
<ul>
<li>Wir haben den RAM (<code>.shared_memory</code>) im Linker-Script reserviert</li>
<li>Wie sagen wir dem Compiler, dass unser Struct genau dort landen soll?</li>
<li>Die Lösung: ein Compiler-spezifisches Attribut (<code>__attribute__</code>)</li>
<li>Wir „nageln“ die Variable physisch auf die Adresse <code>0x38000000</code> fest</li>
</ul>
</div><div class="column" style="width:50%;">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="sourceCode numberSource c number-lines code-with-copy"><code class="sourceCode c"><span id="cb4-1"><a aria-label="1"></a><span class="co">// Die Variable wird zwingend in</span></span>
<span id="cb4-2"><a aria-label="2"></a><span class="co">// die .shared_memory Sektion gelegt!</span></span>
<span id="cb4-3"><a aria-label="3"></a></span>
<span id="cb4-4"><a aria-label="4"></a>__attribute__<span class="op">((</span>section<span class="op">(</span><span class="st">".shared_memory"</span><span class="op">)))</span></span>
<span id="cb4-5"><a aria-label="5"></a><span class="dt">volatile</span> SharedData_t sd<span class="op">;</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div></div>
<aside class="notes">
<p>Ohne Attribut landet die Variable in <code>.bss</code>/<code>.data</code> (oft AXI-SRAM). Mit <code>__attribute__((section(".shared_memory")))</code> zwingt GCC den Linker auf <code>0x38000000</code> — beide Kerne sehen dieselben Bytes.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="das-schlüsselwort-volatile" class="slide level2">
<h2>Das Schlüsselwort volatile</h2>
<ul>
<li>Ein weiteres Problem beim Speichern: der C-Compiler-Optimizer (<code>-O2</code> / <code>-O3</code>)</li>
<li>Der Compiler analysiert den Code einer Task (z.&nbsp;B. auf dem M4)</li>
<li>Er sieht eine <code>while(sd.m7_ready == 0);</code>-Schleife</li>
<li>Er denkt: „In meiner Task ändert niemand diese Variable. Also lese ich sie nur 1× aus dem RAM und nutze danach für immer ein CPU-Register!“ <span class="math inline">\(\rightarrow\)</span> Endlosschleife!</li>
<li>Lösung: <code>volatile</code></li>
<li>Sagt dem Compiler: Diese Variable kann sich jederzeit durch externe Hardware (oder einen anderen Kern) ändern! Lese sie bei JEDEM Zugriff zwingend frisch aus dem RAM!</li>
</ul>
<aside class="notes">
<p>Ohne <code>volatile</code> darf der Optimizer das Flag einmal lesen und danach nur noch das Register prüfen — der M4 friert ein, obwohl der M7 den RAM ändert. <code>volatile</code> erzwingt frische RAM-Reads.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="reicht-volatile-für-multicore" class="slide level2">
<h2>Reicht volatile für Multicore?</h2>
<ul>
<li>Wir haben die Variable im richtigen SRAM platziert (<code>__attribute__</code>)</li>
<li>Wir haben den Compiler gezwungen, immer aus dem RAM zu lesen (<code>volatile</code>)</li>
<li>Sind wir jetzt sicher?</li>
<li>NEIN! Absolut nicht</li>
<li><code>volatile</code> kontrolliert nur den Software-Compiler. Es kontrolliert nicht die Hardware-Caches der CPU!</li>
<li>Hier betreten wir das gefährlichste Feld der Embedded-Entwicklung</li>
</ul>
<aside class="notes">
<p><code>volatile</code> stoppt nur Compiler-Optimierungen — nicht den L1-Cache des M7. Hardware-Puffern bleibt das Multicore-Problem.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="struktur-der-ping-pong-daten" class="slide level2">
<h2>Struktur der Ping-Pong Daten</h2>
<ul>
<li>Für unser Labor bauen wir uns ein C-Struct, das beide Kerne kennen</li>
<li>Beide Kerne binden dieselbe Header-Datei ein!</li>
</ul>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="sourceCode numberSource c number-lines code-with-copy"><code class="sourceCode c"><span id="cb5-1"><a aria-label="1"></a><span class="kw">typedef</span> <span class="kw">struct</span> <span class="op">{</span></span>
<span id="cb5-2"><a aria-label="2"></a>    <span class="dt">uint8_t</span>  m7_ready<span class="op">;</span>      <span class="co">// 1 = M7 hat Daten geschrieben</span></span>
<span id="cb5-3"><a aria-label="3"></a>    <span class="dt">uint8_t</span>  m4_ready<span class="op">;</span>      <span class="co">// 1 = M4 hat Daten geschrieben</span></span>
<span id="cb5-4"><a aria-label="4"></a>    <span class="dt">uint32_t</span> payload_value<span class="op">;</span> <span class="co">// Der eigentliche Wert (Payload)</span></span>
<span id="cb5-5"><a aria-label="5"></a><span class="op">}</span> SharedData_t<span class="op">;</span></span>
<span id="cb5-6"><a aria-label="6"></a></span>
<span id="cb5-7"><a aria-label="7"></a><span class="co">// Im Code (in CM7 und CM4):</span></span>
<span id="cb5-8"><a aria-label="8"></a>__attribute__<span class="op">((</span>section<span class="op">(</span><span class="st">".shared_memory"</span><span class="op">)))</span></span>
<span id="cb5-9"><a aria-label="9"></a><span class="dt">volatile</span> SharedData_t sd<span class="op">;</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<aside class="notes">
<p>Bevor wir uns dem Cache-Problem widmen, hier noch kurz die Datenstruktur für unser heutiges Labor. Wir bauen ein Struct namens <code>SharedData_t</code>. Es enthält ein Flag, mit dem der M7 signalisiert „Ich habe fertig geschrieben“, und ein Flag für den M4. Darunter liegt der eigentliche Payload-Wert. Dieses Struct deklarieren wir als <code>volatile</code> und legen es in die Shared-Memory-Sektion. Achten Sie darauf, dass diese Definition in einer Header-Datei liegt, die in beide Unterprojekte (CM4 und CM7) eingebunden wird. Sonst wissen die Kerne nicht, wie die Bytes im RAM angeordnet sind.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="zusammenfassung-shared-memory" class="slide level2">
<h2>Zusammenfassung: Shared Memory</h2>
<ul>
<li>AMP erfordert physikalischen Datenaustausch, da es kein gemeinsames Betriebssystem gibt</li>
<li>Wir nutzen den SRAM4 (D3-Domäne), da er für beide Kerne gut erreichbar ist</li>
<li>Die Adress-Zuweisung erfolgt über das Linker-Script (<code>.ld</code>) und <code>__attribute__((section))</code></li>
<li>Das Flag <code>NOLOAD</code> schützt den RAM vor dem Überschreiben beim Booten</li>
<li>Das Keyword <code>volatile</code> stoppt gefährliche Compiler-Optimierungen</li>
</ul>
<aside class="notes">
<p>Fassen wir den ersten Teil zusammen. Wir haben die logische Struktur für unsere Inter-Core-Kommunikation gelegt. Wir nutzen den SRAM4 als toten Briefkasten. Wir weisen dem Linker den Weg und hindern den C-Startup-Code am Nullen der Daten. Wenn Sie das auf einem Cortex-M0 oder Cortex-M4 Dual-Core machen würden, wären Sie jetzt fertig. Aber wir haben einen Cortex-M7. Und der M7 bringt ein Feature mit, das uns jetzt das Leben zur Hölle macht.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="was-ist-ein-cpu-cache" class="slide level2">
<h2>Was ist ein CPU-Cache?</h2>
<ul>
<li>Die CPU (Board-Setup z.&nbsp;B. <span class="math inline">\(400\,\mathrm{MHz}\)</span>) ist extrem schnell</li>
<li>Der Hauptspeicher (SRAM) ist langsam (z.&nbsp;B. braucht ein Zugriff <span class="math inline">\(5\)</span> Taktzyklen)</li>
<li>Der L1-Cache:
<ul>
<li>Ein winziger, aber unfassbar schneller SRAM direkt im Prozessorkern (<span class="math inline">\(1\)</span> Taktzyklus)</li>
<li>Wenn die CPU eine Variable aus dem RAM liest, kopiert die Hardware einen ganzen Block (Cache-Line, <span class="math inline">\(32\,\mathrm{Byte}\)</span>) in den Cache</li>
<li>Beim nächsten Lesen wird die Variable aus dem Cache geholt (blitzschnell!)</li>
</ul></li>
</ul>
<aside class="notes">
<p>Bei Board-Setup <span class="math inline">\(\approx 400\,\mathrm{MHz}\)</span> ist SRAM oft mehrere Takte entfernt. L1-Cache (<span class="math inline">\(32\)</span>-Byte-Lines) liefert Folgezugriffe in einem Takt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="write-through-vs.-write-back" class="slide level2">
<h2>Write-Through vs.&nbsp;Write-Back</h2>
<ul>
<li>Was passiert, wenn der C-Code eine Variable schreibt (<code>sd.m7_ready = 1;</code>)?</li>
<li><strong>Write-Through:</strong>
<ul>
<li>Die CPU schreibt den Wert in den Cache UND sofort parallel durch in den Haupt-RAM</li>
<li>(Sicher, aber langsamer)</li>
</ul></li>
<li><strong>Write-Back</strong> (häufig, solange die Region cacheable ist):
<ul>
<li>Die CPU schreibt den Wert NUR in den internen Cache!</li>
<li>Der echte SRAM bleibt veraltet (Stale Data)</li>
<li>Der Cache schreibt die Daten erst in den RAM zurück (Eviction), wenn er Platz für neue Variablen braucht</li>
</ul></li>
</ul>
<aside class="notes">
<p>Das Lesen ist unproblematisch. Aber was passiert beim Schreiben? Hier gibt es in der IT zwei Architekturen. Bei Write-Through schreibt der Cache jede Änderung sofort durch auf den großen SRAM. Das ist sicher, bremst den Bus aber aus. Moderne Prozessoren wie der Cortex-M7 nutzen deshalb standardmäßig Write-Back. Wenn Ihr Code <code>m7_ready = 1</code> ausführt, speichert die Hardware diese „1“ ausschließlich im winzigen L1-Cache des M7. Im echten SRAM auf der Platine steht weiterhin eine „0“. Der L1-Cache behält das für sich, bis er irgendwann voll ist und Platz machen muss. Erst dann schreibt er die Daten in den echten RAM zurück. Und hier beginnt die Katastrophe für unsere Multicore-Kommunikation.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="das-drama-der-cache-kohärenz" class="slide level2">
<h2>Das Drama der Cache-Kohärenz</h2>
<ul>
<li>Das Szenario:
<ul>
<li>Der Cortex-M7 rechnet einen Wert aus und setzt das Flag <code>m7_ready = 1</code></li>
<li>Dank Write-Back landet die 1 nur im L1-Cache des M7. Im SRAM4 steht weiterhin 0</li>
<li>Der Cortex-M4 (ohne Cache) fragt über die Bus-Matrix den SRAM4 ab</li>
<li>Der SRAM4 antwortet mit 0</li>
</ul></li>
<li>Ergebnis: Der M4 wartet ewig. Die Cores sind asynchron. Die Daten sind korrumpiert!</li>
<li>Dieses Problem nennt man einen <em>Cache Coherency Failure</em></li>
</ul>
<aside class="notes">
<p>M7 setzt <code>m7_ready = 1</code> nur im Write-Back-Cache; SRAM4 bleibt 0. M4 liest physisch 0 und wartet ewig — Cache Coherency Failure.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="visualisierung-cache-coherency-failure" class="slide level2">
<h2>Visualisierung: Cache Coherency Failure</h2>
<p><img data-src="../_livefigures/inline-plantuml-74c0316b.svg" class="livefigure"></p>
<ul>
<li>Der M4 sieht die neuen Daten des M7 nicht, da sie im L1-Cache „feststecken“</li>
</ul>
<aside class="notes">
<p>Diagramm: Cache dirty, RAM stale, M4 liest 0 — reines Hardware-/Kohärenz-Problem, kein Compiler-/RTOS-Bug.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="hw-lösung-in-pcs-cache-snooping" class="slide level2">
<h2>HW-Lösung in PCs: Cache-Snooping</h2>
<ul>
<li>Wie löst Ihr Intel-i7 im Laptop das Problem?</li>
<li>Er nutzt Hardware-Snooping (z.&nbsp;B. MESI-Protokoll)</li>
<li>Die Kerne „schnüffeln“ (Snoop) gegenseitig auf dem Bus</li>
<li>Wenn Core 2 den RAM liest, bemerkt Core 1 das, unterbricht den Vorgang, schreibt schnell seinen Cache in den RAM und lässt Core 2 dann erst lesen</li>
<li>Warum hat der STM32H755 das nicht?</li>
<li>Snooping kostet extrem viel Siliziumfläche, viel Strom und (das Schlimmste) verursacht unvorhersehbare Bus-Latenzen <span class="math inline">\(\rightarrow\)</span> Gift für harte Echtzeit!</li>
</ul>
<aside class="notes">
<p>PCs lösen Kohärenz per Hardware-Snooping (z.&nbsp;B. MESI) — teuer, stromhungrig, jitterbehaftet. Auf dem STM32H755 lösen wir es software-/MPU-seitig.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="software-lösung-1-manuelles-management" class="slide level2">
<h2>Software-Lösung 1: Manuelles Management</h2>
<ul>
<li>Wir zwingen den M7 per C-Code, seinen Cache zu leeren</li>
<li>Die <code>core_cm7.h</code>-Bibliothek bietet dafür spezielle CMSIS-Befehle:
<ul>
<li><code>SCB_CleanDCache_by_Addr(...)</code>: Nimm diese Variable aus dem L1-Cache und schreibe sie zwingend sofort in den SRAM durch! (nach dem Schreiben)</li>
<li><code>SCB_InvalidateDCache_by_Addr(...)</code>: Verwirf diese Variable im L1-Cache! Zwinge die CPU, sie beim nächsten Mal direkt aus dem SRAM zu lesen! (vor dem Lesen)</li>
</ul></li>
</ul>
<aside class="notes">
<p>Die erste Möglichkeit, dieses Problem zu lösen, ist manuelles Cache-Management im C-Code. ARM liefert dafür CMSIS-Kern-Funktionen. Wenn der M7 fertig geschrieben hat, rufen wir <code>SCB_CleanDCache_by_Addr</code> auf. Das befiehlt der CPU: Nimm genau diesen Speicherbereich aus dem L1-Cache und schreibe ihn gewaltsam und sofort in den echten SRAM. Umgekehrt, bevor der M7 eine Variable liest, auf die der M4 eventuell geschrieben hat, rufen wir <code>SCB_InvalidateDCache_by_Addr</code> auf. Das erklärt die Cache-Line für ungültig und zwingt die M7-Hardware, den Wert beim nächsten Zugriff physikalisch neu aus dem SRAM zu holen.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="nachteile-der-software-lösung" class="slide level2">
<h2>Nachteile der Software-Lösung</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6"><pre class="sourceCode numberSource c number-lines code-with-copy"><code class="sourceCode c"><span id="cb6-1"><a aria-label="1"></a><span class="co">// Beispielcode M7:</span></span>
<span id="cb6-2"><a aria-label="2"></a>sd<span class="op">.</span>m7_ready <span class="op">=</span> <span class="dv">1</span><span class="op">;</span></span>
<span id="cb6-3"><a aria-label="3"></a><span class="co">// Manuelles Durchschreiben!</span></span>
<span id="cb6-4"><a aria-label="4"></a>SCB_CleanDCache_by_Addr<span class="op">((</span><span class="dt">uint32_t</span><span class="op">*)&amp;</span>sd<span class="op">,</span></span>
<span id="cb6-5"><a aria-label="5"></a>                        <span class="kw">sizeof</span><span class="op">(</span>SharedData_t<span class="op">));</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<ul>
<li>Warum wir das im Labor NICHT machen:
<ul>
<li>Man vergisst es extrem leicht <span class="math inline">\(\rightarrow\)</span> schwer zu findende Bugs</li>
<li>Der Cache arbeitet immer in <span class="math inline">\(32\)</span>-Byte-Blöcken (Cache-Lines). Wenn Ihre Datenstruktur nicht exakt auf <span class="math inline">\(32\)</span> Byte ausgerichtet ist, invalidieren Sie versehentlich auch benachbarte Variablen!</li>
<li>Es kostet unnötig CPU-Taktzyklen</li>
</ul></li>
</ul>
<aside class="notes">
<p>Das manuelle Management funktioniert, ist aber in der Praxis fehleranfällig. Schauen Sie sich den Code an. Sie müssen nach jedem Schreibvorgang diese Clean-Funktion aufrufen. Vergessen Sie es nur an einer einzigen Stelle im Code, haben Sie Ihren Heisenbug. Viel schlimmer ist das <span class="math inline">\(32\)</span>-Byte-Problem. Ein L1-Cache reinigt nie einzelne Bytes, er operiert immer auf <span class="math inline">\(32\)</span>-Byte-Blöcken. Wenn Ihr Struct nur <span class="math inline">\(12\)</span> Byte groß ist und Sie es invalidieren, löscht die CPU auch die <span class="math inline">\(20\)</span> benachbarten Bytes im Cache aus dem RAM. Liegt dort eine völlig unbeteiligte Variable, die die CPU gerade berechnet hat, vernichten Sie Daten! Wir werden diese Software-Lösung heute deshalb nicht verwenden.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="hardware-lösung-2-best-practice-die-mpu" class="slide level2">
<h2>Hardware-Lösung 2 (Best Practice): Die MPU</h2>
<ul>
<li>Wir entziehen dem Cache einfach die Erlaubnis, diesen spezifischen RAM-Bereich (SRAM4) zu puffern!</li>
<li>Das Werkzeug dafür ist die MPU (Memory Protection Unit) im Cortex-M7</li>
<li>Die MPU ist ein Hardware-Modul, das Zugriffsrechte und Cache-Regeln für bestimmte Speicherregionen definiert</li>
<li>Unsere Konfiguration:
<ul>
<li>Wir definieren eine MPU-Region über den Bereich des SRAM4 (<code>0x38000000</code>)</li>
<li>Wir setzen die Eigenschaft auf <em>Disable Cache</em> / <em>Non-Cacheable</em> (ARM: oft TEX/C/B so gesetzt, dass kein Caching erfolgt)</li>
</ul></li>
</ul>
<aside class="notes">
<p>Es gibt einen besseren Weg: Wir lösen das Problem wieder hardwareseitig, aber ohne Snooping. Wir nutzen die Memory Protection Unit, die MPU des Cortex-M7. Die MPU ist eine Art Türsteher im Prozessorkern. Wir können der MPU sagen: Pass auf, der Bereich ab <code>0x38000000</code> gehört zum Shared Memory. Dieser Bereich ist tabu für den Cache! Wir markieren diesen speziellen Teil des RAMs als Non-Cacheable (in CubeMX oft: Disable Cache). Sobald wir das tun, wird die Hardware den L1-Cache für alle Variablen aus diesem Struct schlichtweg umgehen.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="was-bewirkt-die-mpu" class="slide level2">
<h2>Was bewirkt die MPU?</h2>
<ul>
<li>Wenn der M7 nun <code>sd.m7_ready = 1;</code> ausführt:
<ul>
<li>Die MPU sieht die Adresse <code>0x38000000</code></li>
<li>Sie weiß: Cache ist hier verboten!</li>
<li>Sie leitet den Schreibbefehl direkt über die Bus-Matrix an den SRAM4 durch</li>
</ul></li>
<li>Vorteile:
<ul>
<li>Kein C-Code (Clean/Invalidate) mehr nötig!</li>
<li>Cache-Kohärenz ist zu <span class="math inline">\(100\,\%\)</span> physikalisch garantiert</li>
<li>Der M4 sieht die neuen Daten sofort in Echtzeit</li>
</ul></li>
<li>Nachteil: Zugriffe auf das Struct sind langsamer (Bus-Latenz), aber für ein paar Ping-Pong-Flags ist das irrelevant</li>
</ul>
<aside class="notes">
<p>Was passiert nun zur Laufzeit? Der M7 schreibt <code>m7_ready = 1</code>. Der Schreibbefehl geht an den Kern. Der Türsteher, die MPU, sieht die Adresse und leitet den Befehl am L1-Cache vorbei direkt in die AXI-Bus-Matrix bis zum SRAM4. Die 1 landet sofort und ohne Umwege physikalisch im RAM. Das Schöne daran: Unser C-Code bleibt absolut sauber. Wir müssen keine Clean-Funktionen mehr aufrufen. Der einzige Nachteil ist, dass dieser direkte Zugriff <span class="math inline">\(5\)</span> Takte statt <span class="math inline">\(1\)</span> Takt dauert. Aber für die wenigen Bytes an Status-Flags in der Multicore-Kommunikation ist diese minimale Latenz absolut zu verschmerzen.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="laborvorbereitung-der-ping-pong-datenaustausch" class="slide level2">
<h2>Laborvorbereitung: Der Ping-Pong Datenaustausch</h2>
<ul>
<li>Ziel für heute Nachmittag:
<ul>
<li>Beide Kerne wecken</li>
<li>Shared Memory konfigurieren</li>
<li>Daten hin- und herspielen (Ping-Pong mit Handshake-Flags)</li>
</ul></li>
</ul>
<aside class="notes">
<p>Damit sind wir bei der Vorbereitung für das heutige Labor angekommen. Wir werden den STM32H755 in seiner ganzen asymmetrischen Pracht nutzen: Shared Memory, Linker-Sektion, MPU und ein kontrolliertes Handshake zwischen M7 und M4.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="schritt-1-cubemx-dual-core-setup" class="slide level2">
<h2>Schritt 1: CubeMX Dual-Core Setup</h2>
<ul>
<li>Starten Sie ein Projekt für das Board (mit beiden Cores M7 &amp; M4)</li>
<li>Unter Middleware <span class="math inline">\(\rightarrow\)</span> FreeRTOS:
<ul>
<li>Aktivieren Sie FreeRTOS ausschließlich für den Cortex-M4</li>
<li>Den M7 lassen wir komplett Bare-Metal laufen! (Asymmetric OS-Design)</li>
</ul></li>
</ul>
<aside class="notes">
<p>Legen Sie ein neues Projekt an und aktivieren Sie beide Kerne. Wir setzen heute ein klassisches Industrie-Pattern um: FreeRTOS ausschließlich auf dem M4-Kern für die harte Echtzeit. Den M7-Kern lassen wir als hochperformantes Bare-Metal-Programm völlig ohne Betriebssystem laufen.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="schritt-2-den-cortex-m4-wecken" class="slide level2">
<h2>Schritt 2: Den Cortex-M4 wecken</h2>
<ul>
<li>In der generierten Struktur öffnen Sie die <code>main.c</code> im Ordner CM7</li>
<li>Fügen Sie ganz am Anfang der <code>main()</code> den Weckruf ein!</li>
</ul>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7"><pre class="sourceCode numberSource c number-lines code-with-copy"><code class="sourceCode c"><span id="cb7-1"><a aria-label="1"></a><span class="dt">int</span> main<span class="op">(</span><span class="dt">void</span><span class="op">)</span></span>
<span id="cb7-2"><a aria-label="2"></a><span class="op">{</span></span>
<span id="cb7-3"><a aria-label="3"></a>  HAL_Init<span class="op">();</span></span>
<span id="cb7-4"><a aria-label="4"></a>  SystemClock_Config<span class="op">();</span></span>
<span id="cb7-5"><a aria-label="5"></a></span>
<span id="cb7-6"><a aria-label="6"></a>  <span class="co">// WICHTIG: M4 aus dem Hardware-Reset befreien!</span></span>
<span id="cb7-7"><a aria-label="7"></a>  HAL_PWREx_ReleaseCore<span class="op">(</span>PWR_CORE_CPU2<span class="op">);</span></span>
<span id="cb7-8"><a aria-label="8"></a></span>
<span id="cb7-9"><a aria-label="9"></a>  <span class="co">// ... restlicher Code des M7</span></span>
<span id="cb7-10"><a aria-label="10"></a><span class="op">}</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<aside class="notes">
<p>Der erste Programmierschritt im Labor ist extrem wichtig: Öffnen Sie den Ordner für den CM7. In dessen <code>main</code>-Funktion hat der Codegenerator bereits die HAL-Initialisierung und den System-Clock konfiguriert. Darunter müssen Sie den M4-Kern aufwecken, indem Sie die Hardware-Reset-Linie lösen. Rufen Sie <code>HAL_PWREx_ReleaseCore</code> auf. Ab dieser Mikrosekunde laufen beide Kerne gleichzeitig.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="schritt-3-shared-memory-struct-anlegen" class="slide level2">
<h2>Schritt 3: Shared Memory Struct anlegen</h2>
<ul>
<li>Legen Sie eine neue Datei <code>shared_data.h</code> im <code>Common/Inc</code>-Ordner an</li>
<li>Binden Sie diese Header-Datei in der <code>main.c</code> beider Kerne ein</li>
</ul>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb8"><pre class="sourceCode numberSource c number-lines code-with-copy"><code class="sourceCode c"><span id="cb8-1"><a aria-label="1"></a><span class="pp">#ifndef SHARED_DATA_H</span></span>
<span id="cb8-2"><a aria-label="2"></a><span class="pp">#define SHARED_DATA_H</span></span>
<span id="cb8-3"><a aria-label="3"></a></span>
<span id="cb8-4"><a aria-label="4"></a><span class="pp">#include </span><span class="im">&lt;stdint.h&gt;</span></span>
<span id="cb8-5"><a aria-label="5"></a></span>
<span id="cb8-6"><a aria-label="6"></a><span class="kw">typedef</span> <span class="kw">struct</span> <span class="op">{</span></span>
<span id="cb8-7"><a aria-label="7"></a>    <span class="dt">uint8_t</span> m7_ready<span class="op">;</span></span>
<span id="cb8-8"><a aria-label="8"></a>    <span class="dt">uint8_t</span> m4_ready<span class="op">;</span></span>
<span id="cb8-9"><a aria-label="9"></a>    <span class="dt">uint32_t</span> payload_value<span class="op">;</span></span>
<span id="cb8-10"><a aria-label="10"></a><span class="op">}</span> SharedData_t<span class="op">;</span></span>
<span id="cb8-11"><a aria-label="11"></a></span>
<span id="cb8-12"><a aria-label="12"></a><span class="co">// Deklaration mit Sektions-Zuweisung</span></span>
<span id="cb8-13"><a aria-label="13"></a><span class="kw">extern</span> __attribute__<span class="op">((</span>section<span class="op">(</span><span class="st">".shared_memory"</span><span class="op">)))</span></span>
<span id="cb8-14"><a aria-label="14"></a>       <span class="dt">volatile</span> SharedData_t sd<span class="op">;</span></span>
<span id="cb8-15"><a aria-label="15"></a></span>
<span id="cb8-16"><a aria-label="16"></a><span class="pp">#endif</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<aside class="notes">
<p>In Schritt 3 definieren wir unsere Sprache. Da beide Kerne völlig getrennte C-Projekte sind, müssen wir eine Header-Datei im Common-Ordner anlegen, auf den beide Zugriff haben. Wir definieren unser Struct <code>SharedData_t</code> mit den Bereit-Flags und einem Payload. Darunter deklarieren wir die Variable <code>sd</code> als <code>extern</code>, binden sie fest an die <code>.shared_memory</code>-Sektion und markieren sie als <code>volatile</code>. Damit haben beide Kerne dasselbe logische Verständnis der Datenstruktur. Hinweis: Die Definition (ohne <code>extern</code>) gehört in genau eine <code>.c</code>-Datei, typischerweise im Common-Ordner.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="schritt-4-das-linker-script-anpassen" class="slide level2">
<h2>Schritt 4: Das Linker-Script anpassen</h2>
<ul>
<li>Öffnen Sie in beiden Projekten (CM7 und CM4) die Datei <code>STM32H755..._FLASH.ld</code></li>
<li>Fügen Sie im <code>MEMORY</code>-Block den SRAM4 hinzu (CubeMX-Name: <code>RAM_D3</code>; entscheidend ist die Adresse <code>0x38000000</code>):</li>
</ul>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb9"><pre class="sourceCode numberSource ld number-lines code-with-copy"><code class="sourceCode"><span id="cb9-1"><a aria-label="1"></a>RAM_D3 (xrw) : ORIGIN = 0x38000000, LENGTH = 64K</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<ul>
<li>Fügen Sie im <code>SECTIONS</code>-Block unsere Sektion ein (Achtung auf <code>NOLOAD</code>!):</li>
</ul>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb10"><pre class="sourceCode numberSource ld number-lines code-with-copy"><code class="sourceCode"><span id="cb10-1"><a aria-label="1"></a>.shared_memory (NOLOAD) :</span>
<span id="cb10-2"><a aria-label="2"></a>{</span>
<span id="cb10-3"><a aria-label="3"></a>  . = ALIGN(4);</span>
<span id="cb10-4"><a aria-label="4"></a>  *(.shared_memory)</span>
<span id="cb10-5"><a aria-label="5"></a>} &gt; RAM_D3</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<aside class="notes">
<p>Nun müssen wir den Worten im C-Code auch Taten im Linker-Script folgen lassen. Suchen Sie die <code>.ld</code>-Dateien im Projektbaum. Fügen Sie im <code>MEMORY</code>-Block den D3-RAM ein, beginnend bei <code>0x38000000</code>. Dann scrollen Sie runter in den <code>SECTIONS</code>-Block und fügen unsere Sektion <code>.shared_memory</code> ein. Vergessen Sie das <code>NOLOAD</code> nicht, sonst überschreibt der M4-Bootcode den SRAM4 mit Nullen und zerschießt die Daten, die der M7 vielleicht schon geschrieben hat. Sie müssen diese Änderungen zwingend in den Linker-Scripten beider Kerne vornehmen!</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="schritt-5-die-ping-pong-logik-cortex-m4" class="slide level2">
<h2>Schritt 5: Die Ping-Pong Logik (Cortex-M4)</h2>
<ul>
<li>In der FreeRTOS-Task des M4:</li>
</ul>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb11"><pre class="sourceCode numberSource c number-lines code-with-copy"><code class="sourceCode c"><span id="cb11-1"><a aria-label="1"></a><span class="dt">void</span> StartDefaultTask<span class="op">(</span><span class="dt">void</span> <span class="op">*</span>argument<span class="op">)</span> <span class="op">{</span></span>
<span id="cb11-2"><a aria-label="2"></a>  <span class="cf">for</span><span class="op">(;;)</span> <span class="op">{</span></span>
<span id="cb11-3"><a aria-label="3"></a>    <span class="co">// 1. Warten bis M7 Daten bereitstellt</span></span>
<span id="cb11-4"><a aria-label="4"></a>    <span class="cf">while</span><span class="op">(</span>sd<span class="op">.</span>m7_ready <span class="op">==</span> <span class="dv">0</span><span class="op">)</span> <span class="op">{</span></span>
<span id="cb11-5"><a aria-label="5"></a>      osDelay<span class="op">(</span><span class="dv">1</span><span class="op">);</span> <span class="co">// Task schlafen, CPU nicht blockieren</span></span>
<span id="cb11-6"><a aria-label="6"></a>    <span class="op">}</span></span>
<span id="cb11-7"><a aria-label="7"></a></span>
<span id="cb11-8"><a aria-label="8"></a>    <span class="co">// 2. Daten verarbeiten</span></span>
<span id="cb11-9"><a aria-label="9"></a>    sd<span class="op">.</span>m7_ready <span class="op">=</span> <span class="dv">0</span><span class="op">;</span> <span class="co">// Quittieren</span></span>
<span id="cb11-10"><a aria-label="10"></a>    sd<span class="op">.</span>payload_value <span class="op">+=</span> <span class="dv">1</span><span class="op">;</span></span>
<span id="cb11-11"><a aria-label="11"></a></span>
<span id="cb11-12"><a aria-label="12"></a>    <span class="co">// 3. Antwort an M7 signalisieren</span></span>
<span id="cb11-13"><a aria-label="13"></a>    sd<span class="op">.</span>m4_ready <span class="op">=</span> <span class="dv">1</span><span class="op">;</span></span>
<span id="cb11-14"><a aria-label="14"></a>  <span class="op">}</span></span>
<span id="cb11-15"><a aria-label="15"></a><span class="op">}</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<aside class="notes">
<p>Kommen wir zur eigentlichen Logik. Auf dem M4 läuft unser FreeRTOS. In der generierten Task bauen wir eine Warteschleife. Solange der M7 noch keine Daten geliefert hat (<code>m7_ready == 0</code>), schicken wir die Task mit <code>osDelay(1)</code> schlafen. So belasten wir die Echtzeit-Umgebung des M4 nicht mit ewigem Busy-Polling. Sobald das Flag auf 1 springt, wachen wir auf. Wir löschen das M7-Flag (Quittierung), addieren eine 1 auf den Payload-Wert und setzen unser eigenes Bereit-Flag <code>m4_ready</code> auf 1. Der Ball liegt wieder beim M7.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="schritt-6-die-ping-pong-logik-cortex-m7" class="slide level2">
<h2>Schritt 6: Die Ping-Pong Logik (Cortex-M7)</h2>
<ul>
<li>In der Super-Loop (<code>while(1)</code>) des M7:</li>
</ul>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb12"><pre class="sourceCode numberSource c number-lines code-with-copy"><code class="sourceCode c"><span id="cb12-1"><a aria-label="1"></a><span class="co">// Initiale Übergabe</span></span>
<span id="cb12-2"><a aria-label="2"></a>sd<span class="op">.</span>payload_value <span class="op">=</span> <span class="dv">0</span><span class="op">;</span></span>
<span id="cb12-3"><a aria-label="3"></a>sd<span class="op">.</span>m7_ready <span class="op">=</span> <span class="dv">1</span><span class="op">;</span></span>
<span id="cb12-4"><a aria-label="4"></a></span>
<span id="cb12-5"><a aria-label="5"></a><span class="cf">while</span> <span class="op">(</span><span class="dv">1</span><span class="op">)</span> <span class="op">{</span></span>
<span id="cb12-6"><a aria-label="6"></a>  <span class="co">// 1. M7 hat kein OS! Polling ist hier (als Demo) ok.</span></span>
<span id="cb12-7"><a aria-label="7"></a>  <span class="cf">if</span><span class="op">(</span>sd<span class="op">.</span>m4_ready <span class="op">==</span> <span class="dv">1</span><span class="op">)</span> <span class="op">{</span></span>
<span id="cb12-8"><a aria-label="8"></a></span>
<span id="cb12-9"><a aria-label="9"></a>    printf<span class="op">(</span><span class="st">"M4 hat geantwortet: </span><span class="sc">%lu\n</span><span class="st">"</span><span class="op">,</span></span>
<span id="cb12-10"><a aria-label="10"></a>           <span class="op">(</span><span class="dt">unsigned</span> <span class="dt">long</span><span class="op">)</span>sd<span class="op">.</span>payload_value<span class="op">);</span></span>
<span id="cb12-11"><a aria-label="11"></a></span>
<span id="cb12-12"><a aria-label="12"></a>    sd<span class="op">.</span>m4_ready <span class="op">=</span> <span class="dv">0</span><span class="op">;</span> <span class="co">// Quittieren</span></span>
<span id="cb12-13"><a aria-label="13"></a>    sd<span class="op">.</span>payload_value <span class="op">+=</span> <span class="dv">1</span><span class="op">;</span></span>
<span id="cb12-14"><a aria-label="14"></a></span>
<span id="cb12-15"><a aria-label="15"></a>    HAL_Delay<span class="op">(</span><span class="dv">500</span><span class="op">);</span> <span class="co">// Demo: Lesbarkeit am Terminal</span></span>
<span id="cb12-16"><a aria-label="16"></a>    sd<span class="op">.</span>m7_ready <span class="op">=</span> <span class="dv">1</span><span class="op">;</span> <span class="co">// Ball zurück zu M4!</span></span>
<span id="cb12-17"><a aria-label="17"></a>  <span class="op">}</span></span>
<span id="cb12-18"><a aria-label="18"></a><span class="op">}</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<aside class="notes">
<p>Das Gegenstück auf dem M7 ist reines Bare-Metal. Wir initiieren das Spiel vor der While-Schleife, indem wir den Payload auf 0 setzen und den Ball losspielen (<code>m7_ready = 1</code>). In der Super-Loop pollen wir das Flag des M4. Da wir auf dem M7 kein Betriebssystem haben, ist das Polling hier in Ordnung. Wenn der M4 geantwortet hat, drucken wir den Wert über UART aus, quittieren das Flag, addieren wieder eine 1, machen absichtlich ein <code>HAL_Delay</code> (nur Demo, Bare-Metal!), damit wir die Ausgabe am Terminal mitlesen können, und spielen den Ball zurück zum M4.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="schritt-7-mpu-im-m7-konfigurieren" class="slide level2">
<h2>Schritt 7: MPU im M7 konfigurieren</h2>
<ul>
<li>Ohne diese Konfiguration wird der Code aus Schritt 6 scheitern!</li>
<li>Gehen Sie im CubeMX Configurator auf: System Core <span class="math inline">\(\rightarrow\)</span> CORTEX_M7 <span class="math inline">\(\rightarrow\)</span> Reiter MPU Control</li>
<li>Aktivieren Sie Region 0:
<ul>
<li>Base Address: <code>0x38000000</code></li>
<li>Size: <span class="math inline">\(64\,\mathrm{KB}\)</span></li>
<li>Access Permission: ALL ACCESS</li>
<li>TEX / Shareable / Cacheable: Disable Cache (Non-Cacheable)</li>
</ul></li>
<li>Code neu generieren!</li>
</ul>
<aside class="notes">
<p>Würden wir den Code jetzt flashen, würde absolut nichts passieren. Das System friert ein — wegen des Cache-Kohärenz-Problems. Um das zu beheben, müssen wir in den Configurator der CubeIDE. Unter System Core finden Sie die Cortex-M7-Einstellungen. Dort gehen Sie in das Memory Protection Unit Control. Wir legen eine neue Regel an: Für den Bereich beginnend bei <code>0x38000000</code> mit einer Größe von <span class="math inline">\(64\,\mathrm{KB}\)</span> stellen wir das Caching-Verhalten auf Disable Cache. Generieren Sie den Code. Ab jetzt umgeht die M7-Hardware den L1-Cache komplett, wenn sie auf unser <code>sd</code>-Struct zugreift.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="flashen-debuggen-im-labor" class="slide level2">
<h2>Flashen &amp; Debuggen im Labor</h2>
<ul>
<li>Klicken Sie im CM7-Projekt auf den kleinen Pfeil neben dem Käfer-Icon (Debug) und wählen Sie „Debug Configurations“</li>
<li>Die CubeIDE hat automatisch eine Startup-Gruppe angelegt</li>
<li>Achten Sie darauf, dass beide <code>.elf</code>-Dateien (CM7 und CM4) angewählt sind</li>
<li>Ein Klick lädt erst den M7 in den Flash (Bank 1), danach den M4 (Bank 2) und stoppt beide an ihrer jeweiligen <code>main()</code></li>
<li>Drücken Sie auf beiden Konsolen auf Play (Resume)</li>
</ul>
<aside class="notes">
<p>Das Flashen eines Dual-Core-Projekts bedarf eines kleinen Tricks in Eclipse. Sie dürfen nicht einfach blind auf Run klicken, sonst flashen Sie vielleicht nur den M7. Gehen Sie in die Debug Configurations. ST hat dort meist schon eine Multicore-Startgruppe angelegt. Vergewissern Sie sich, dass die Checkboxen für beide Firmware-Dateien, also <code>CM7.elf</code> und <code>CM4.elf</code>, gesetzt sind. Wenn Sie starten, brennt der ST-Link zuerst Programm 1 und dann Programm 2 in den Chip. Dann halten beide Kerne in der ersten Zeile Code an. Sie müssen dann oben in der Taskleiste beide Kerne separat auf Resume drücken, damit das Ping-Pong-Spiel beginnt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="mutwilliger-fehler-mpu-deaktivieren" class="slide level2">
<h2>Mutwilliger Fehler: MPU deaktivieren</h2>
<ul>
<li>Wenn Ihr System läuft und der UART fröhlich zählt:</li>
<li>Gehen Sie in den Code und kommentieren Sie die MPU-Initialisierung aus:</li>
</ul>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb13"><pre class="sourceCode numberSource c number-lines code-with-copy"><code class="sourceCode c"><span id="cb13-1"><a aria-label="1"></a><span class="co">/* HAL_MPU_Enable(MPU_PRIVILEGED_DEFAULT); */</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<ul>
<li>Die Beobachtung:
<ul>
<li>Der M7 gibt initial 0 aus und friert dann für immer ein</li>
<li>Der M4 wartet ewig im <code>osDelay(1)</code></li>
</ul></li>
<li>Sie haben den berüchtigten Cache Coherency Failure live am Debugger!</li>
</ul>
<aside class="notes">
<p>Wenn Ihr Terminal im Labor anfängt, im <span class="math inline">\(500\,\mathrm{ms}\)</span>-Takt die Zahlen hochzuzählen, haben Sie es geschafft. Beide Kerne reden miteinander. Um sich aber zu beweisen, dass die Theorie stimmt, machen wir einen mutwilligen Fehler. Gehen Sie in die <code>main.c</code> des M7 und kommentieren Sie die Zeile aus, in der die MPU aktiviert wird (<code>HAL_MPU_Enable</code>). Flashen Sie das Programm neu. Das Terminal wird stumm bleiben. Der M7 schreibt in seinen L1-Cache, der M4 liest aus dem SRAM4 die alten Nullen aus. Beide hängen in ihren While-Schleifen fest. Sie haben gerade den berüchtigtsten Architektur-Fehler der Multicore-Entwicklung live erzeugt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="die-gefahr-für-nächste-woche-hsem" class="slide level2">
<h2>Die Gefahr für nächste Woche (HSEM)</h2>
<ul>
<li>Unser Ping-Pong heute nutzt ein strenges Handshake-Protokoll (<code>m7_ready</code>, <code>m4_ready</code>). Jeder Kern weiß genau, wann er schreiben darf</li>
<li>Was passiert aber…
<ul>
<li>wenn beide Kerne asynchron arbeiten und gleichzeitig <code>sd.payload_value</code> überschreiben wollen?</li>
</ul></li>
<li>Ein FreeRTOS-Mutex hilft hier nicht! (Der M7 hat ja gar kein FreeRTOS!)</li>
<li>Wir brauchen hardware-basierte Schlösser, die über Core-Grenzen hinweg funktionieren (HSEM)</li>
<li><span class="math inline">\(\rightarrow\)</span> Thema für Vorlesung 8!</li>
</ul>
<aside class="notes">
<p>Das heutige Labor ist ein kontrolliertes Ping-Pong. Die Fahne <code>m7_ready</code> sorgt dafür, dass immer nur ein Kern zur selben Zeit in das Struct schreibt. Aber was passiert nächste Woche, wenn beide Kerne völlig asynchron und unabhängig voneinander auf denselben Payload-Wert zugreifen wollen? Dann haben wir eine Multicore Race Condition. Unser schöner FreeRTOS-Mutex aus Woche 4 hilft uns hier keinen Millimeter weiter. Der Mutex existiert ja nur im RAM des M4-Kerns, der Bare-Metal-M7 weiß davon gar nichts. Wir benötigen ein Schloss, das auf Hardware-Ebene in Silizium gegossen ist und über Bus-Grenzen hinweg funktioniert. Das nennt sich Hardware Semaphores (HSEM) und wird das große Thema in Vorlesung 8 sein.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="zusammenfassung-des-tages" class="slide level2">
<h2>Zusammenfassung des Tages</h2>
<ul>
<li>AMP ist der Standard für harte Echtzeit-Multicore-Systeme, um Interferenzen zwischen Betriebssystemen zu vermeiden</li>
<li>Der Cortex-M4 übernimmt oft das RTOS, der Cortex-M7 (Bare-Metal) kümmert sich um den Durchsatz</li>
<li>Die Adress-Zuordnung von geteilten Daten muss hart über <code>.ld</code>-Linker-Skripte erzwungen werden (<code>.shared_memory</code>)</li>
<li>Cache-Kohärenz zerschießt die Kommunikation, wenn schnelle Kerne (M7) Write-Back-Caches nutzen</li>
<li>Die Lösung ist die Deaktivierung des Caches für den geteilten RAM per Hardware (MPU)</li>
</ul>
<aside class="notes">
<p>Fassen wir zusammen. Sie kennen nun den fundamentalen Architektur-Unterschied zwischen dem Laptop zu Hause (SMP) und dem Steuergerät im Labor (AMP). Sie können den Boot-Ablauf eines Dual-Core-Chips orchestrieren. Sie verstehen, wie man per C-Attribut Daten in spezifische SRAM-Sektoren zwingt. Und das Wichtigste: Sie haben verstanden, warum ein L1-Cache uns die Datenkonsistenz zerstört und wie wir das durch die Memory Protection Unit auf Hardware-Ebene sauber und professionell beheben können. Damit sind Sie perfekt gewappnet für das Labor am Nachmittag!</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>


</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="../assets/dhbw_logo.svg" class="slide-logo"></p>
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': true,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1280,

        height: 720,

        // Factor of the display size that should remain empty around the content
        margin: 8.0e-2,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script>
    /**
     * Fit Quarto/Reveal Mermaid SVGs to remaining slide space.
     * Dimensions from getBoundingClientRect are viewport pixels; CSS sizes inside
     * Reveal slides are unscaled — divide by Reveal.getScale().
     */
    (function () {
      const BOTTOM_PAD = 36;
      const SIDE_PAD_RATIO = 0.92;
      const MAX_SCALE = 3.4;

      function presentSlide() {
        var present = document.querySelector("section.present");
        if (!present) return null;
        var nested = present.querySelector(":scope > section.present");
        return nested || present;
      }

      function revealScale() {
        if (window.Reveal && typeof Reveal.getScale === "function") {
          var s = Reveal.getScale();
          return s > 0.05 ? s : 1;
        }
        return 1;
      }

      function ensureWrap(svg) {
        var parent = svg.parentElement;
        if (!parent) return null;
        if (parent.classList.contains("mermaid-fit")) return parent;
        var wrap = document.createElement("div");
        wrap.className = "mermaid-fit";
        parent.insertBefore(wrap, svg);
        wrap.appendChild(svg);
        return wrap;
      }

      function contentBottomAbove(slide, wrap) {
        var top = slide.getBoundingClientRect().top;
        var bottom = top + 8;
        var children = slide.children;
        for (var i = 0; i < children.length; i++) {
          var el = children[i];
          if (el === wrap || el.classList.contains("mermaid-fit")) break;
          if (el.querySelector && el.querySelector("svg.mermaid-js")) break;
          if (el.tagName === "ASIDE") continue;
          var r = el.getBoundingClientRect();
          if (r.height > 1) bottom = Math.max(bottom, r.bottom);
        }
        return bottom;
      }

      function naturalSize(svg) {
        if (svg.dataset.natW && svg.dataset.natH) {
          return { w: +svg.dataset.natW, h: +svg.dataset.natH };
        }
        var vb = svg.viewBox && svg.viewBox.baseVal;
        if (vb && vb.width > 0 && vb.height > 0) {
          svg.dataset.natW = String(vb.width);
          svg.dataset.natH = String(vb.height);
          return { w: vb.width, h: vb.height };
        }
        var wAttr = parseFloat(svg.getAttribute("width"));
        var hAttr = parseFloat(svg.getAttribute("height"));
        if (wAttr > 0 && hAttr > 0) {
          svg.dataset.natW = String(wAttr);
          svg.dataset.natH = String(hAttr);
          return { w: wAttr, h: hAttr };
        }
        var r = svg.getBoundingClientRect();
        var rs = revealScale();
        var w = r.width / rs || 320;
        var h = r.height / rs || 120;
        svg.dataset.natW = String(w);
        svg.dataset.natH = String(h);
        return { w: w, h: h };
      }

      function fitMermaids() {
        var slide = presentSlide();
        if (!slide) return;

        var rs = revealScale();
        var slideRect = slide.getBoundingClientRect();
        var svgs = slide.querySelectorAll("svg.mermaid-js");

        for (var i = 0; i < svgs.length; i++) {
          var svg = svgs[i];
          var wrap = ensureWrap(svg);
          if (!wrap) continue;

          svg.style.removeProperty("transform");
          svg.style.removeProperty("max-width");
          svg.style.removeProperty("zoom");
          wrap.style.zoom = "";

          var nat = naturalSize(svg);
          var above = contentBottomAbove(slide, wrap);
          var availW = (slideRect.width * SIDE_PAD_RATIO) / rs;
          var availH = Math.max(72, (slideRect.bottom - above - BOTTOM_PAD) / rs);

          var scale = Math.min(availW / nat.w, availH / nat.h, MAX_SCALE);
          if (!(scale > 0)) scale = 1;

          var targetW = Math.max(1, Math.round(nat.w * scale));
          var targetH = Math.max(1, Math.round(nat.h * scale));

          svg.setAttribute("width", targetW);
          svg.setAttribute("height", targetH);
          svg.style.width = targetW + "px";
          svg.style.height = targetH + "px";
          svg.style.display = "block";
          svg.style.margin = "0.35rem auto 0";
        }
      }

      function scheduleFit() {
        requestAnimationFrame(function () {
          fitMermaids();
          setTimeout(fitMermaids, 150);
          setTimeout(fitMermaids, 500);
          setTimeout(fitMermaids, 1100);
        });
      }

      window.addEventListener("load", scheduleFit);

      function bindReveal() {
        if (!window.Reveal || !Reveal.on) return false;
        Reveal.on("ready", scheduleFit);
        Reveal.on("slidechanged", scheduleFit);
        if (Reveal.isReady && Reveal.isReady()) scheduleFit();
        return true;
      }

      if (!bindReveal()) {
        window.addEventListener("load", function () {
          var tries = 0;
          var id = setInterval(function () {
            if (bindReveal() || ++tries > 50) clearInterval(id);
          }, 100);
        });
      }

      window.dhbwMermaidFit = fitMermaids;
    })();
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp("https:\/\/dantschi\.github\.io\/echtzeitsysteme\/");
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>