<!DOCTYPE html>
<html lang="en"><head>
<link href="../assets/dhbw_logo.svg" rel="icon" type="image/svg+xml">
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-bf27225e3a48a9273f3daa8f8e829971.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-contrib/livefigures-0.8.0/livefigures.css" rel="stylesheet"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.10.19">

  <meta name="author" content="Prof.&nbsp;Dr.-Ing. Daniel Klünder">
  <title>Echtzeitsysteme – 07 · Tracing und Timing-Analyse</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: 1.5em;}
    div.column{flex: auto;}
    @media screen {
    div.columns{gap: min(4vw, 1.5em);}
    div.column{overflow-x: auto;}
    }
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="../site_libs/revealjs/dist/theme/quarto-f355cf95444bdbe7a358cd689c441e6f.css">
  <link href="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <script src="../site_libs/quarto-diagram/mermaid.min.js"></script>
  <script src="../site_libs/quarto-diagram/mermaid-init.js"></script>
  <link href="../site_libs/quarto-diagram/mermaid.css" rel="stylesheet">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&amp;display=swap" rel="stylesheet">
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">07 · Tracing und Timing-Analyse</h1>
  <p class="subtitle">Beobachten, ohne die Messung mit der Ursache zu verwechseln · EZS · DHBW Stuttgart</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Prof.&nbsp;Dr.-Ing. Daniel Klünder
</div>
</div>
</div>

</section>
<section id="willkommen-in-der-systemanalyse" class="slide level2">
<h2>Willkommen in der Systemanalyse!</h2>
<ul>
<li>Siebter Termin: eine Messfrage stellen, eine Quelle wählen, die Grenze nennen</li>
<li>Zielchip wie in VL6: STM32H755, M7 Bare-Metal, M4 FreeRTOS</li>
<li>Ein Trace ist Evidenz für <strong>beobachtete</strong> Läufe</li>
<li>Er ist kein WCET-Beweis und kein Normenstempel</li>
<li>Im Repo liegen kein winIDEA-Projekt und kein BlueBox-Modell</li>
</ul>
<aside class="notes">
<p>Die Leitfrage lautet: Was geschieht wann, und was belegt die Beobachtung wirklich? Das Ping-Pong-System aus Vorlesung 6 bleibt das Beispiel. Der M7 läuft Bare Metal, also ohne RTOS-Kernel. Der M4 nutzt FreeRTOS über CMSIS-RTOS2. RTOS heißt Real-Time Operating System. Ein Trace ist eine geordnete Aufzeichnung von Ereignissen. Vollständigkeit und Zeitbasis müssen geprüft werden. WCET, Worst-Case Execution Time, ist eine obere Schranke unter benannten Annahmen. Ein Trace einzelner Läufe ist diese Schranke nicht.</p>
<p>Ein Heisenbug ist ein Fehler, dessen Erscheinung sich durch die Beobachtung ändert, weil Code, Layout oder Zeit sich ändern. Das ist keine Quantenbehauptung. Drei Lernziele: ein Verfahren wählen, Zeitgrößen auseinanderrechnen und die Grenze der Aussage nennen. Eine fehlende BlueBox ist eine offene Laborentscheidung, kein Hindernis für die Begriffe.</p>
<p>Die Agenda führt vom Einfluss der Beobachtung zur Auswertung.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="agenda-für-heute" class="slide level2">
<h2>Agenda für heute</h2>
<ol type="1">
<li>Einfluss der Beobachtung</li>
<li>CoreSight: ITM, DWT, ETM</li>
<li>Was eine Zahl bedeutet</li>
<li>Werkzeugkette und Zeitbasis</li>
<li>OS-Sicht und Labor, mit offenen Hardwarepunkten</li>
</ol>
<aside class="notes">
<p>ITM, Instrumentation Trace Macrocell, nimmt Softwaredaten entgegen. DWT, Data Watchpoint and Trace, meldet konfigurierte Kernereignisse. ETM, Embedded Trace Macrocell, trägt komprimierten Kontrollfluss. OS ist das Betriebssystem, hier der M4-Kernel. Die Reihenfolge ist absichtlich: zuerst, wie Beobachtung den Ablauf verändert, dann wo Ereignisse entstehen, dann was Zeitmarken bedeuten, zuletzt wie Werkzeuge sie darstellen.</p>
<p>Leitfrage für den Tag: Eine M4-Task reagiert spät. Ist das Rechenzeit, Wartezeit, Scheduling oder ein Messartefakt? Die UART-Rechnung mit „Hallo“ und etwa 434 µs gehört zur printf-Folie. Sie ist Leitungszeit, nicht CPU-Zeit, und ersetzt diese Agenda nicht.</p>
<p>Die Ausgangsarchitektur liefert mehrere Beobachtungspunkte.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="recap-unser-multicore-system" class="slide level2">
<h2>Recap: Unser Multicore-System</h2>
<ul>
<li>VL6: Ownership, Barriere, non-cacheable Region</li>
<li>Heute beobachten wir denselben Vertrag</li>
<li>DWT sieht konfigurierte <strong>CPU-Zugriffe</strong> des gewählten Kerns</li>
<li>DWT beweist nicht, was im SRAM hinter dem M7-Cache steht</li>
<li>Ein Dual-Core-Debug beweist weder parallelen Trace noch SWO</li>
</ul>
<div class="cell" data-reveal="true" data-fig-width="8.2" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'theme': 'base', 'themeVariables': {'background': '#FFFFFF', 'primaryColor': '#FFFFFF', 'primaryBorderColor': '#E5E5EA', 'primaryTextColor': '#1D1D1F', 'lineColor': '#86868B'}}}%%
flowchart LR
  M7["M7-Store und Cachekopie"] --&gt; DWT["DWT sieht den Kernzugriff"]
  M7 --&gt; SRAM["Shared-SRAM"]
  SRAM --&gt; M4["M4-Lesewert"]
  DAP["DAP-Fenster"] --&gt; SRAM
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<aside class="notes">
<p>Drei Orte bleiben getrennt. Der M7 kann eine Cachekopie haben. SRAM, Static Random Access Memory, ist der gemeinsam erreichbare Speicher. Der M4 liest seine eigene Sicht. DWT beobachtet konfigurierte Zugriffe des gewählten Kerns. MPU, Memory Protection Unit, macht im Basislabor die Shared-Region nicht cachebar. IPC, Inter-Processor Communication, ist der vereinbarte Kanal aus Vorlesung 6: Besitz, Barriere, dann der Zustand. Ein Paket „M7 schreibt 1“ belegt diesen Kernzugriff, nicht die aktuelle Lesekopie des M4 und nicht jeden Speicherweg. Ein DAP-Fenster, Debug Access Port, ist eine weitere Sicht und kann den Bus belasten. Dass beide Kerne debuggbar sind, heißt nicht, dass zwei Tracequellen gleichzeitig aufgenommen und korreliert decodiert werden.</p>
<p>Jede gewählte Beobachtung hat eigene Eingriffe und Grenzen.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="beobachtung-verändert-softwareabläufe" class="slide level2">
<h2>Beobachtung verändert Softwareabläufe</h2>
<p>Analogie, kein physikalisches Gesetz für jede Messung:</p>
<ul>
<li>extra Befehle, Logs, anderes Scheduling</li>
<li>anderes Layout, anderer Cachezustand</li>
<li>Halt, Buszugriffe des Debuggers, voller Tracepuffer</li>
</ul>
<p>GPIO, Zykluszähler, ITM, DWT und ETM beantworten verschiedene Fragen und stören verschieden stark.</p>
<aside class="notes">
<p>Die Analogie ist kurz: Beobachten kann den Gegenstand verändern. In Software sind das zusätzliche Befehle, Logpuffer, Locks, Buszugriffe, ein anderes Layout oder Cachebild und ein angehaltener Kern. GPIO, General-Purpose Input/Output, setzt eine Pinflanke. ITM nimmt Softwarestimuli entgegen. DWT und ETM können Ereignisse ohne diese Marker liefern, brauchen aber Aktivierung, Filter und einen Puffer. „Ohne zusätzliche Anwendungsbefehle und ohne Halt“ ist eine mögliche Eigenschaft eines Hardwarepfads, nicht der Satz „Einfluss exakt null“. Ein voller Puffer kann verlieren oder, je nach Aufbau, den Kern verzögern. ITM-Softwarestimuli sind instrumentiert. Der ganze ITM-Baustein ist deshalb nicht pauschal „immer nur Software“, weil weitere Ereignisquellen über ihn laufen können.</p>
<p>Zwei Mechanismen: Eine Ausgabe verlängert eine Taskphase. Ein Debughalt ändert die Reihenfolge zwischen den Kernen.</p>
<p>printf liefert dafür ein Größenbeispiel.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="klassisches-debugging-die-printf-gefahr" class="slide level2">
<h2>Klassisches Debugging: Die <code>printf</code>-Gefahr</h2>
<p>„Hallo“, 8N1: 5 Byte = 50 Bit.</p>
<p><span class="math display">\[50 / 115200 \approx 434\,\text{µs}\]</span></p>
<p>Das ist die <strong>Übertragungsdauer</strong>, nicht automatisch CPU-Zeit und nicht der Halt des Chips.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Weg</th>
<th>CPU während der Bits</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Polling</td>
<td>bleibt in der Ausgabe</td>
</tr>
<tr class="even">
<td>IRQ</td>
<td>kurz, UART läuft weiter</td>
</tr>
<tr class="odd">
<td>DMA</td>
<td>Start kurz, Transfer ohne CPU</td>
</tr>
</tbody>
</table>
<p>Formatierung, Locks und Puffer kommen dazu. <code>printf</code> ist auf dem zeitkritischen Messpfad ungeeignet. Außerhalb bleibt begrenztes Logging möglich.</p>
<p>Ein verpasster Termin ist ein Deadline Miss, kein automatischer Crash.</p>
<aside class="notes">
<p>UART, Universal Asynchronous Receiver/Transmitter, ist die serielle Leitung. 8N1 heißt acht Datenbits, keine Parität, ein Stopbit. Mit dem Startbit sind das zehn Bits je Byte. „Hallo“ sind fünf ASCII-Bytes, ohne Nullterminator und ohne Zeilenumbruch. 5 mal 10 gleich 50 Bit. 50 geteilt durch 115200 Bit je Sekunde sind etwa 434 µs. Das ist die reine Leitungsdauer, nicht die CPU-Zeit der Formatierung und nicht ein Halt des Chips. IRQ ist die Interruptanforderung, DMA der direkte Speicherzugriff. Polling belegt die CPU während der Bits. IRQ und DMA verkürzen die CPU-Phase, sind aber nicht aufwandfrei. Treiber und Locks können trotzdem blockieren.</p>
<p>Im Lehrbild: 10 µs Rechnen plus 434 µs blockierende Ausgabe ergeben etwa 444 µs gegen eine angenommene Frist von 50 µs. Ein verpasster Termin ist ein Deadline Miss, kein automatischer Absturz.</p>
<p>Ein Zeitdiagramm macht die Verlängerung sichtbar.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="visualisierung-der-beobachter-effekt" class="slide level2">
<h2>Visualisierung: Der Beobachter-Effekt</h2>
<p>Synthetisches Modell, keine Messung. Die zweite Spur bricht die Achse: gleiche Kästchen sind nicht gleiche Zeiten.</p>
<p><img data-src="../_livefigures/inline-plantuml-2b70a0f5.svg" class="livefigure"></p>
<p><img data-src="../_livefigures/inline-plantuml-d53fabc4.svg" class="livefigure"></p>
<table class="caption-top">
<colgroup>
<col style="width: 26%">
<col style="width: 21%">
<col style="width: 18%">
<col style="width: 34%">
</colgroup>
<thead>
<tr class="header">
<th>Variante</th>
<th>Inhalt</th>
<th style="text-align: right;">Dauer</th>
<th style="text-align: center;">Frist 50 µs</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>ohne Ausgabe</td>
<td>Rechnung</td>
<td style="text-align: right;">10 µs</td>
<td style="text-align: center;">gehalten</td>
</tr>
<tr class="even">
<td>mit blockierendem „Hallo“</td>
<td>10 µs plus 434 µs Leitung</td>
<td style="text-align: right;">etwa 444 µs</td>
<td style="text-align: center;">gerissen</td>
</tr>
</tbody>
</table>
<p>Der GPIO-Puls von HIGH bis LOW ist die Zeit zwischen physischen Pinflanken. Präemption, Bus, Pad und die Auflösung des Messgeräts liegen darin. Das Messgerät sieht nicht die beiden CPU-Storezeitpunkte.</p>
<aside class="notes">
<p>Die Tabelle ist ein synthetisches Modell, keine Messung. Ohne Ausgabe dauert die Rechnung 10 µs und hält die Frist von 50 µs. Mit blockierendem „Hallo“ kommen etwa 434 µs Leitung dazu, zusammen etwa 444 µs. Der lange Balken ist nicht maßstabsgleich zum kurzen. Ein Achsenbruch ist deshalb benannt. GPIO ist der Pin, BSRR, Bit Set/Reset Register, ein direkter Set- oder Reset-Zugriff, HAL die Abstraktionsschicht. Der gemessene Puls läuft von der physischen steigenden zur fallenden Flanke. Präemption zwischen den Marken liegt darin. Bus, Pad und die Auflösung des Messgeräts auch. Das Gerät sieht nicht die beiden Store-Zeitpunkte der CPU. Eine reine Store-zu-Store-Zeit wäre eine andere Definition.</p>
<p>Frage: Warum kann der GPIO-Puls länger sein als die CPU-Zeit der Funktion? Weil Unterbrechungen zwischen den Marken liegen und die Flanke später am Pin ankommt als der Store.</p>
<p>Ein Breakpoint greift noch stärker ein.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="klassisches-debugging-breakpoints" class="slide level2">
<h2>Klassisches Debugging: Breakpoints</h2>
<ul>
<li>Der <strong>betroffene</strong> Kern hält an</li>
<li>Der andere Kern, DMA und Peripherie können weiterlaufen</li>
<li>DBGMCU kann einzelne Timer oder Watchdogs einfrieren, wenn das so konfiguriert ist</li>
<li>Der NVIC ist keine unbegrenzte FIFO: Pending kann Flanken zusammenfassen</li>
<li>Puffer können überlaufen</li>
<li>Pending und Peripherie-FIFOs speichern nur begrenzt. Viele Flanken erzeugen nicht automatisch viele verschachtelte Stackframes.</li>
</ul>
<p>Nach Resume ist nur rekonstruierbar, was noch in Registern, FIFOs oder Pending steht.</p>
<aside class="notes">
<p>Ein Breakpoint hält den betroffenen Kern an. Der andere Kern, DMA und die Peripherie können weiterlaufen. DBGMCU ist der Debug-Support-Block des STM32 und kann einzelne Timer oder Watchdogs einfrieren, wenn das Bit gesetzt ist. Der NVIC, Nested Vectored Interrupt Controller, ist keine unbegrenzte FIFO. FIFO heißt First In, First Out. Ein Pending-Bit merkt sich, dass etwas anliegt, nicht jede Flanke als eigene Zahl. Peripherie-FIFOs und Statusregister haben eigene Grenzen. Viele Flanken erzeugen nicht automatisch viele verschachtelte Stackframes, weil der Kern die ISRs nicht betritt. ISR ist die Behandlungsroutine. Nach Resume ist nur da, was Register, FIFOs oder Pending noch halten. Verlorene Flanken kommen nicht zurück.</p>
<p>Frage: Welche Ereignisse sind nach dem Weiterlaufen noch da? Nur die, die ein begrenzter Speicher noch enthält, nicht jede verlorene Flanke.</p>
<p>Das folgende Bild trennt anhaltende Hardware von angehaltener Software.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="das-problem-des-halt-states" class="slide level2">
<h2>Das Problem des “Halt-States”</h2>
<p>Lehrschema. Freeze gilt nur, wenn das passende Bit gesetzt ist. Es gibt keine unbegrenzte Interrupt-Warteschlange.</p>
<p><img data-src="../_livefigures/inline-plantuml-4d9f8366.svg" class="livefigure"></p>
<aside class="notes">
<p>Die Grafik zeigt den haltenden Kern und daneben UART, DMA und den anderen Kern, die weiterlaufen können. Externe Flanken landen im Pending und nicht als unbegrenzte Liste. Eine zweite Variante friert den Timer nur, wenn das Freeze-Bit gesetzt ist. DAP, Debug Access Port, und SWD, Serial Wire Debug, sind der Debugzugriff. Ein laufendes Speicherlesen über DAP ist kein Breakpoint. SWD heißt nicht, dass jeder Zugriff den Kern anhält. Der Verkehr kann trotzdem den Bus belasten und ist keine lückenlose Vergangenheit. Resume stellt verworfene Daten nicht wieder her. Cross-Trigger, der weitere Kerne mit anhält, ist eine Konfiguration, kein Automatismus. UART ist die serielle Schnittstelle, DMA der Kopierer.</p>
<p>Halt, DAP-Lesen, Softwarelog und Hardwaretrace sind vier verschiedene Eingriffe.</p>
<p>Solche Eingriffe können einen Fehler verschwinden lassen.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="der-heisenbug" class="slide level2">
<h2>Der Heisenbug</h2>
<ul>
<li>Der Fehler verschwindet, weil die Beobachtung die Zeit oder das Layout ändert</li>
<li>Race: verschränkte Zugriffe ohne Vertrag</li>
<li>Priority Inversion: ein Lock plus Verdrängung des Owners</li>
<li>Beides kann heikel zu beobachten sein, beides ist nicht dasselbe</li>
</ul>
<aside class="notes">
<p>Ein Heisenbug verschwindet, weil die Beobachtung Zeit oder Layout ändert. Zwei Beispiele bleiben getrennt. Race: zwei Teilnehmer schreiben ohne gültigen Vertrag, und ein Log verschiebt ihre Reihenfolge. Priority Inversion: eine hohe Task wartet auf ein Lock, das eine niedrige hält, und eine mittlere verdrängt den Besitzer. Lock ist die Sperre, Owner der Besitzer, Präemption die Verdrängung. RTOS ist der Kernel, der diese Zustände führt. Beides kann schwer zu beobachten sein. Es ist nicht derselbe Mechanismus. Dass der Fehler im Debugger weg ist, beweist die Ursache nicht.</p>
<p>Kleine Softwaremarkierungen können gezielter sein. Auch sie müssen selbst untersucht werden.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="der-workaround-software-instrumentierung" class="slide level2">
<h2>Der Workaround: Software Instrumentierung</h2>
<ul>
<li>GPIO und Zähler beantworten „wann bin ich hier?“</li>
<li>ITM schreibt Stimulus-Wörter, es formatiert keinen Text</li>
<li><code>ITM_SendChar</code> kann auf freie Kapazität <strong>warten</strong></li>
<li>Voller Puffer ist keine „winzige Seltenheit“</li>
<li>Laborvariante, wenn wir sie nutzen: nicht blockieren, Drops zählen, Statusbits der vorhandenen CMSIS-Version prüfen</li>
</ul>
<aside class="notes">
<p>Ein Marker ist zusätzliche Arbeit im Zielprogramm. GPIO setzt eine Flanke. ITM, Instrumentation Trace Macrocell, nimmt Datenwörter an einem Stimulusport entgegen und formatiert nicht selbst den Text. CMSIS ist die Arm-Schnittstelle. <code>ITM_SendChar</code> kann in der vorhandenen Implementierung auf freien Platz warten. Eine nicht blockierende Lehrvariante macht höchstens einen Versuch, zählt bei fehlender Kapazität einen Drop und wartet nicht. Mehrere Schreiber oder eine ISR brauchen einen eigenen Vertrag. <code>volatile</code> macht den Zähler nicht racefrei. SWO, Serial Wire Output, ist der serielle Traceausgang und muss samt Empfänger nachgewiesen sein, bevor wir ihn zusagen.</p>
<p>Manche Fragen brauchen Ereignisse ohne solche Marker.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="wir-brauchen-non-intrusive-observation" class="slide level2">
<h2>Wir brauchen: Non-Intrusive Observation</h2>
<p>Präzise Formulierung:</p>
<ul>
<li>ohne extra Anwendungsbefehle</li>
<li>ohne den Kern anzuhalten</li>
<li>nicht: Einfluss immer exakt null</li>
</ul>
<p>Prüfen: Trace an, Pfad, Puffer, Überlauf, Stall.</p>
<aside class="notes">
<p>Non-intrusive meint hier: bestimmte Ereignisse ohne zusätzliche Anwendungsbefehle und ohne Halt des Kerns. Aktivierung, Filter, Transport und Speicher bleiben nötig. DWT und ETM können solche Kernereignisse liefern. ITM-Softwarestimuli gehören nicht in diese Definition, weil die Anwendung schreibt. Andere ITM-Funktionen dürfen deshalb nicht pauschal als „immer Software“ abgetan werden. Ein voller Puffer kann verlieren. Ob er den Kern anhält, einen Stall, hängt vom Aufbau ab. Das sagen wir nicht für jeden Recorder.</p>
<p>Die Zusammenfassung ordnet die vier Beobachtungsarten.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="zusammenfassung-block-1" class="slide level2">
<h2>Zusammenfassung Block 1</h2>
<ul>
<li>434 µs sind Leitungszeit von „Hallo“</li>
<li>Halt stoppt nicht den ganzen Chip</li>
<li>GPIO misst ein Intervall, keine reine CPU-Zeit</li>
<li>Hardwaretrace ist eine Quelle mit eigenen Verlusten</li>
</ul>
<aside class="notes">
<p>Vier Ergebnisse: Die UART-Leitung von „Hallo“ dauert etwa 434 µs. Ein Halt verändert den Systemzustand und stoppt nicht den ganzen Chip. Ein GPIO-Puls ist ein Intervall zwischen Pinflanken, inklusive Präemption. Ein Hardwaretrace ist eine gefilterte Ereignisquelle mit eigenen Verlusten, keine vollständige Historie. UART, GPIO, ITM, DWT und ETM bleiben die Namen dieser Wege.</p>
<p>Frage: Warum kann der GPIO-Puls länger sein als die CPU-Zeit der Funktion? Weil Unterbrechungen zwischen den Marken liegen und Pad sowie Messgerät dazukommen.</p>
<p>Jetzt trennen wir die Tracequellen und ihre Wege.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="hardware-trace-arm-coresight" class="slide level2">
<h2>Hardware-Trace: ARM CoreSight</h2>
<div class="cell" data-reveal="true" data-fig-width="9.2" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'theme': 'base', 'themeVariables': {'background': '#FFFFFF', 'primaryColor': '#FFFFFF', 'primaryBorderColor': '#E5E5EA', 'primaryTextColor': '#1D1D1F', 'lineColor': '#86868B'}}}%%
flowchart LR
  SW[Software] --&gt; ITM
  CPU[CPU-Zugriffe und Ereignisse] --&gt; DWT
  DWT --&gt; PF[Tracepfad]
  ITM --&gt; PF
  CF[Kontrollfluss] --&gt; ETM
  ETM --&gt; PF
  PF --&gt; OUT[TPIU oder anderer Sink]
  DAP[Debugzugriffe] --&gt; BUS[Bus]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>Nicht drei gleiche Spione am SRAM. DWT sitzt an der konfigurierten Quelle <strong>des Kerns</strong>.</p>
<p>Was fehlt: DMA-Schreiben, der andere Kern, Cachezeilen hinter dem Store, alles außerhalb des Filters.</p>
<aside class="notes">
<p>CoreSight ist die Debug- und Tracearchitektur von Arm. ITM nimmt Softwarestimuli, DWT konfigurierte Kernereignisse, ETM den Kontrollfluss. TPIU, Trace Port Interface Unit, kann der Ausgang der Tracedaten sein. Ein Sink ist der Empfänger oder Speicher, nicht zwingend die TPIU. DAP, der Debug Access Port, liest und schreibt über den Bus und ist kein Ereignisstrom. Die Grafik ist ein Konzept, kein verdrahtetes Nucleo. Ob DWT, ITM und ETM auf dem H755 genau so verbunden sind, prüft RM0399 der Projektrevision. DWT sieht nicht automatisch DMA und nicht den anderen Kern. Gleichzeitiger Trace beider Kerne ist offen.</p>
<p>Debugschnittstelle, Traceausgang und Stecker sind verschiedene Ebenen.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="jtag-vs.-swd-vs.-trace" class="slide level2">
<h2>JTAG vs.&nbsp;SWD vs.&nbsp;Trace</h2>
<table class="caption-top">
<colgroup>
<col style="width: 13%">
<col style="width: 44%">
<col style="width: 41%">
</colgroup>
<thead>
<tr class="header">
<th>Weg</th>
<th>transportiert</th>
<th>beweist nicht</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>SWD/JTAG</td>
<td>Debug</td>
<td>lückenlosen Trace</td>
</tr>
<tr class="even">
<td>SWO</td>
<td>oft ITM/DWT</td>
<td>volles ETM</td>
</tr>
<tr class="odd">
<td>parallele Trace-Pins</td>
<td>hohe Rate, wenn vorhanden</td>
<td>dass das Nucleo sie hat</td>
</tr>
<tr class="even">
<td>interner Puffer</td>
<td>kurz, on-chip</td>
<td>lange Historie</td>
</tr>
</tbody>
</table>
<p>UM2408: STDC14/MIPI10 am NUCLEO-H755ZI-Q ist kein Nachweis eines 20-poligen parallelen Trace-Steckers. Pinout, Raster und Adapter am Schaltplan prüfen. Pinmux, ST-LINK-Trennung, GND, VTref, Pegel, Reset.</p>
<aside class="notes">
<p>JTAG, Joint Test Action Group, und SWD, Serial Wire Debug, sind Debugprotokolle. SWO, Serial Wire Output, ist ein serieller Traceausgang und nicht die SWD-Datenleitung. Bei manchen Cortex-M teilt sich SWO den Pin mit JTAG-TDO. Paralleler Trace braucht einen anderen, bestätigten Pfad. GND ist Masse, VTref die Referenzspannung des Targets, Reset die Rücksetzleitung. Die Tabelle trennt, was transportiert wird, von dem, was nicht bewiesen ist. UM2408 beschreibt am NUCLEO-H755ZI-Q STDC14 und MIPI10. Das ist kein Nachweis eines 20-poligen parallelen Trace-Steckers. Pinout und Adapter stehen im Schaltplan der Boardrevision. Ein interner Puffer ist implementationsabhängig und kurz. Einen Stecker, den das Board nicht hat, zeichnen wir nicht.</p>
<p>ITM zeigt als Nächstes, wie Softwaremarker in den Pfad gelangen.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="modul-1-das-itm-instrumentation-trace" class="slide level2">
<h2>Modul 1: Das ITM (Instrumentation Trace)</h2>
<ul>
<li>Stimulus-Port</li>
<li>Software muss schreiben</li>
<li>Warten oder Verwerfen ist eine Implementierungsentscheidung</li>
<li>Drops dokumentieren, sonst sieht die Lücke wie „nichts passiert“ aus</li>
</ul>
<aside class="notes">
<p>ITM heißt Instrumentation Trace Macrocell. Ein Stimulusport ist ein adressierter Eingang für Softwaredaten. Die Anwendung schreibt, die ITM bildet Pakete, der Transport bringt sie zum Empfänger, die Software stellt sie dar. ITM formatiert nicht selbst „Hallo“. CMSIS-<code>ITM_SendChar</code> kann warten. Eine andere Implementierung kann verwerfen. Ein Dropzähler, ein ausgeschalteter Kanal und ein fehlender Empfänger sind drei Zustände. Der Zähler sagt nicht, welche Ereignisse fehlen. Die Softwarestimuli sind instrumentiert. Der Baustein kann weitere Ereignisse transportieren. Die Bits der Cube-CMSIS-Version benennen wir erst, wenn die Header vorliegen. SWO ist der mögliche serielle Ausgang.</p>
<p>DWT erzeugt dagegen Ereignisse aus konfigurierten Kernzugriffen.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="modul-2-das-dwt-data-watchpoint-trace" class="slide level2">
<h2>Modul 2: Das DWT (Data Watchpoint &amp; Trace)</h2>
<ul>
<li>Wenige Komparatoren, Konflikt mit Watchpoints</li>
<li>Adresse, Breite, Richtung, Maske, Datenwert und Zeitstempel hängen von der Implementierung ab</li>
<li>Sie sehen nicht automatisch den anderen Kern oder DMA</li>
<li>Ein M7-Store „1“ kann im Trace stehen, während Write-Back den Wert dem M4 vorenthält</li>
<li>Eine flache Kurve beweist nicht „SRAM blieb 0“</li>
</ul>
<p>Fehlende Pakete können auch heißen: falscher Kern, falsche Adresse, zu spät aufgenommen, Filter, Verlust, Kapazität.</p>
<div class="cell" data-reveal="true" data-fig-width="8.2" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'theme': 'base', 'themeVariables': {'background': '#FFFFFF', 'primaryColor': '#FFFFFF', 'primaryBorderColor': '#E5E5EA', 'primaryTextColor': '#1D1D1F', 'lineColor': '#86868B'}}}%%
flowchart TB
  ST["M7-Store Wert 1, aufgenommen"] --&gt; C["Dirty-Cachekopie"]
  C -.-&gt; S["SRAM kann noch 0 sein"]
  S --&gt; M4["M4 liest seine Sicht"]
  MISS["fehlendes Paket"] --&gt; U["Wert unbekannt, nicht 0"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<aside class="notes">
<p>DWT heißt Data Watchpoint and Trace. Die Komparatoren sind wenige und können mit Watchpoints kollidieren. Ein vollständiger Filter nennt Kern, Adresse, Breite, Richtung und ob Wert oder Zeit im Paket steckt. Die Adresse kommt aus <code>offsetof</code> und der Map, nicht aus einem geratenen Symbol. ELF ist das geladene Image. CPU ist der beobachtete Kern. DMA und der andere Kern sind unsichtbar. SRAM ist der Speicher, den der M4 sehen kann. Ein M7-Store mit Wert 1 kann in einer Dirty-Cachekopie liegen. Die MPU-Basis aus Vorlesung 6 macht den Lehrkanal nicht cachebar. Eine flache Kurve ohne Anfangspaket ist kein Beweis, dass der SRAM 0 blieb. Ein Debugger-Speicherfenster ist ein weiterer Zugriff und kann Cachewartung auslösen.</p>
<p>ETM betrachtet als Nächstes den Kontrollfluss.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="modul-3-das-etm-embedded-trace" class="slide level2">
<h2>Modul 3: Das ETM (Embedded Trace)</h2>
<ul>
<li>Komprimierter Kontrollfluss, plus Sync, Ausnahme, manchmal Zeit</li>
<li>Nicht „ein Bit pro Sprung“</li>
<li>400 MHz sind 400 Millionen <strong>Takte</strong>, nicht Instruktionen</li>
<li>Hypothetisches Modell: 400e6 Ereignisse mal 4 Byte = 1,6 GB/s, nicht die echte ETM-Rate und nicht Gbit/s</li>
</ul>
<p>Rekonstruktion braucht das passende Maschinenbild, die Protokollversion und einen vollständigen Abschnitt. Eine Lücke ist ein unbekannter Abschnitt, keine erfundene Gerade.</p>
<aside class="notes">
<p>ETM heißt Embedded Trace Macrocell. Sie liefert komprimierten Kontrollfluss, keine Kopie jeder Instruktion als langes Paket. ELF ist das Maschinenbild, mit dem der Decoder die Sprünge rekonstruiert. 400 MHz sind 400 Millionen Takte je Sekunde, nicht 400 Millionen Instruktionen. Die Rechnung 400 Millionen Ereignisse mal 4 Byte gleich 1,6 GB/s ist ein hypothetischer Überschlag, keine ETM-Bitrate. Instruction Trace enthält nicht automatisch einen Zeitstempel je Befehl. Cycle-accurate und Timestamp sind Extra-Fähigkeiten und werden nicht versprochen. Eine C-Zeile ist keine einzelne Instruktion. GCC und Optimierung verändern die Zuordnung.</p>
<p>Ein kleines Zweigbeispiel zeigt die Rekonstruktion.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="etm-komprimiert-den-kontrollfluss" class="slide level2">
<h2>ETM komprimiert den Kontrollfluss</h2>
<p>Schema, kein echtes Paketformat. Der graue Abschnitt ist verloren und wird nicht interpoliert.</p>
<div class="cell" data-reveal="true" data-fig-width="8.4" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'theme': 'base', 'themeVariables': {'background': '#FFFFFF', 'primaryColor': '#FFFFFF', 'primaryBorderColor': '#E5E5EA', 'primaryTextColor': '#1D1D1F', 'lineColor': '#86868B'}}}%%
flowchart LR
  C["C: if a"] --&gt; TH["mehrere Thumb-Befehle"]
  TH --&gt; EV["symbolische Traceereignisse"]
  EV --&gt; OK["Decoder mit passender ELF"]
  EV --&gt; GAP["Sync verloren: unbekannt"]
  GAP --&gt; NEU["neuer Abschnitt nach Resync"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>Eine C-Zeile kann mehreren Befehlen entsprechen. Ohne das ELF des <strong>denselben</strong> Builds rekonstruiert das Tool den Pfad nicht.</p>
<p>Sync-Verlust: Strecke grau lassen.</p>
<aside class="notes">
<p>Das Schema trennt C-Text, symbolische Thumb-Befehle, vereinfachte Traceereignisse und den Decoder mit der passenden ELF. Es ist kein echtes ETM-Paketformat. ELF ist das Image, GCC der Compiler. Die Option <code>-g</code> fügt Debuginfo hinzu und macht aus einer Zeile nicht genau einen Befehl. <code>-g</code> und <code>-O2</code> gehen zusammen. Gemessen wird das Image, das wirklich läuft, nicht ein zweiter Debug-Build. Inlining und wegoptimierte Variablen bleiben. Jeder Kern braucht seine eigene ELF. Ein grauer Abschnitt ist verlorene Synchronisation und wird nicht interpoliert. Nach nachgewiesener Resynchronisation kann ein späterer Abschnitt separat gelten.</p>
<p>Die Ereignisse müssen über einen vorhandenen Ausgang zum Recorder.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="die-tpiu-und-der-physikalische-stecker" class="slide level2">
<h2>Die TPIU und der physikalische Stecker</h2>
<ul>
<li>TPIU ist ein möglicher Ausgang, nicht der Beweis, dass jede Spur dort ankommt</li>
<li>Laboraufbau erst zeichnen, wenn Adapter, Active Probe und BlueBox-Modell feststehen</li>
<li>iC5700: Ethernet-Angabe nicht als Gigabit übernehmen, solange die Gerätebeschreibung der <strong>vorliegenden</strong> Hardwareversion das nicht sagt</li>
<li>FNet, Host-Ethernet und Target-Trace sind drei Kabelklassen</li>
<li>Einschalten und Ausschalten nur nach der Anleitung des vorhandenen Geräts. Ohne Gerät ist das keine Laboranweisung.</li>
<li>Keine Preisvergleiche</li>
</ul>
<p>Schema der Rollen. Unbestätigte Kästen bleiben offen. Kein erfundener Stecker.</p>
<div class="cell" data-reveal="true" data-fig-width="8.6" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'theme': 'base', 'themeVariables': {'background': '#FFFFFF', 'primaryColor': '#FFFFFF', 'primaryBorderColor': '#E5E5EA', 'primaryTextColor': '#1D1D1F', 'lineColor': '#86868B'}}}%%
flowchart LR
  T["Target, Tracequelle"] --&gt; A["Ausgang: offen, Board prüfen"]
  A --&gt; P["Probe oder Adapter: offen"]
  P --&gt; R["Recorder: Modell offen"]
  R --&gt; H["Host-Software"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<aside class="notes">
<p>TPIU, Trace Port Interface Unit, kann der Ausgang der Tracedaten auf dem Chip sein. Danach kommen Leitung, Probe oder Adapter, Recorder und Host. FNet und FBridge sind Produktwege des Zubehörs, kein beliebiges Host-Ethernet. Eine Geschwindigkeit der iC5700 übernehmen wir nicht, solange Hardwareversion und Anleitung fehlen. Das Bild hier zeigt Rollen. Ein verifizierter Aufbau nennt Geräte und Leitungen. Externe Digitaleingänge zeichnen wir nur, wenn das Modul vorhanden ist. Im Repository ist es nicht vorhanden. Ein- und Ausschaltreihenfolge kommt aus der Anleitung des realen Geräts, nicht aus dieser Folie. GND, VTref und Reset haben den Zweck, Pegel und Startzustand zu prüfen.</p>
<p>Die Zusammenfassung verbindet Quelle und zulässige Schlussfolgerung.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="zusammenfassung-coresight" class="slide level2" data-background-color="#F5F5F7">
<h2>Zusammenfassung CoreSight</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Quelle</th>
<th>erfasst</th>
<th>beweist nicht</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>ITM</td>
<td>geschriebene Stimuli</td>
<td>rückwirkungsfreie App</td>
</tr>
<tr class="even">
<td>DWT</td>
<td>gefilterte CPU-Ereignisse</td>
<td>SRAM hinter dem Cache</td>
</tr>
<tr class="odd">
<td>ETM</td>
<td>Kontrollfluss, soweit komplett</td>
<td>jede C-Zeile in µs</td>
</tr>
<tr class="even">
<td>DAP</td>
<td>momentane Sicht</td>
<td>Historie</td>
</tr>
</tbody>
</table>
<aside class="notes">
<p>ITM-Softwarestimuli belegen, dass ein Marker ausgeführt und aufgenommen wurde. DWT zeigt konfigurierte Kernereignisse, nicht den ganzen SRAM und nicht DMA. ETM rekonstruiert Kontrollfluss nur in gültigen Abschnitten und mit dem passenden Maschinenbild. DAP liefert eine aktuelle Sicht auf einem benannten Zugriffsweg, keine Vergangenheit. CPU ist der Kern, dessen Zugriffe gemeint sind. Keine Quelle beweist allein, dass das System die Frist hält.</p>
<p>Frage: Warum beweist ein M7-Store keine M4-Sichtbarkeit? Weil eine Write-Back-Kopie und die MPU dazwischen liegen. In der nicht cachebaren Basis sieht der M4 den SRAM. In der absichtlich cachebaren Fehlervariante kann er den alten Wert lesen.</p>
<p>Es folgt, was die Zahlen für Anforderungen bedeuten.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="warum-systemanalyse-und-nachvollziehbare-nachweise-wichtig-sind" class="slide level2">
<h2>Warum Systemanalyse und nachvollziehbare Nachweise wichtig sind</h2>
<p>Normen motivieren Nachweise. Sie sind hier keine Rechtsauskunft.</p>
<ul>
<li>ISO 26262: Straßenfahrzeuge, nicht „jede Software ist illegal“</li>
<li>DO-178C: Luftfahrt-Software, Einordnung über DO-330 und AC 20-115D</li>
<li>IEC 61508: funktionale Sicherheit, nicht pauschal der Medizinstandard</li>
</ul>
<p>Trace ist keines dieser Dokumente als einziges Pflichtwerkzeug. Aussagen nur mit Ausgabe und Abschnitt, wenn wir sie wirklich zitieren. Das tun wir hier nicht im Detail.</p>
<aside class="notes">
<p>Eine Anforderung braucht einen nachvollziehbaren Nachweis, nicht ein Fenster als Stempel. ISO, International Organization for Standardization, ordnet ISO 26262 der Straßenfahrzeug-Funktionsicherheit zu. IEC, International Electrotechnical Commission, ordnet IEC 61508 der funktionalen Sicherheit zu. FAA, Federal Aviation Administration, und AC, Advisory Circular, gehören zum Luftfahrtkontext. DO-178C ist der zugehörige Softwarestandard, DO-330 die Werkzeugqualifikation. Wir zitieren keine Klausel und behaupten keine Konformität. Die NASA-Quelle später ist ein historisches DO-178B-Tutorial. Der didaktische Punkt: Eine Messung beantwortet einen Ausschnitt und braucht benannte Bedingungen. Ein Tracefenster beweist nicht „ISO-konform“.</p>
<p>Die erste Timinggröße ist ein beobachtetes Maximum, keine WCET.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="metrik-1-beobachtetes-laufzeitmaximum" class="slide level2">
<h2>Metrik 1: Beobachtetes Laufzeitmaximum</h2>
<p><span class="math inline">\(\max(C_{\mathrm{beobachtet}})\)</span> ist das Maximum <strong>dieser</strong> Läufe.</p>
<p>Es ist keine obere Schranke für alle zulässigen Ausführungen. Ein ungetesteter Pfad kann länger sein.</p>
<p>Synthetische Stichprobe, keine Messung: 12 µs, 15 µs, 14 µs. Das beobachtete Maximum ist 15 µs und keine WCET.</p>
<p>Der RM-Test bleibt der aus VL2: hinreichend <span class="math inline">\(n(2^{1/n}-1)\)</span>, Grenzwert <span class="math inline">\(\ln 2 \approx 69{,}3\,\%\)</span> für große <span class="math inline">\(n\)</span>. Ein Messmaximum ohne konservative Absicherung ist kein <span class="math inline">\(C_i\)</span> für diesen Beweis.</p>
<aside class="notes">
<p>WCET, Worst-Case Execution Time, ist die obere Grenze über alle zulässigen Ausführungen unter festgelegten Annahmen. Das Maximum einer endlichen Stichprobe ist eine andere Zahl. Pfad, Eingabe, Cache, Interruptlast und die Messdefinition ändern sie. Eine kleine synthetische Stichprobe zeigt einen größten Balken und keine Garantie für die unbekannte Menge. RM, Rate Monotonic, ist das Scheduling nach der Periode und nicht die Handbuchnummer RM0399. Der hinreichende Test aus Vorlesung 2 lautet <span class="math inline">\(n(2^{1/n}-1)\)</span> und nähert sich für großes <span class="math inline">\(n\)</span> dem Wert <span class="math inline">\(\ln 2\)</span>, etwa 69,3 Prozent. Er ist hinreichend, nicht notwendig. Ein Messmaximum ohne konservative Begründung ist kein <span class="math inline">\(C_i\)</span> für diesen Beweis. Eine Million Läufe zeichnet kein garantiertes Ende. Qualität heißt: Sync, passende ELF, keine Lücken in der Summe, bekannte Zeitbasis.</p>
<p>Fristen beziehen sich auf die Antwort ab Freigabe, nicht nur auf einen Funktionsabschnitt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="metrik-2-deadline-verifizierung" class="slide level2">
<h2>Metrik 2: Deadline-Verifizierung</h2>
<p>Job: Freigabe <span class="math inline">\(r\)</span>, Start <span class="math inline">\(s\)</span>, Fertig <span class="math inline">\(f\)</span>, Deadline <span class="math inline">\(d = r + D\)</span>.</p>
<p><span class="math display">\[R = f - r, \qquad \text{Slack} = d - f\]</span></p>
<p>Ein negativer Slack verletzt <strong>diese</strong> Frist. Daraus folgt kein „illegal im Straßenverkehr“.</p>
<p>OS-Awareness kennt Freigabe und Deadline nicht von selbst. Die Ereignisse müssen im Trace oder im Protokoll liegen.</p>
<aside class="notes">
<p>Ein Job ist eine Aktivierung einer Task. <span class="math inline">\(r\)</span> ist die Freigabe, <span class="math inline">\(s\)</span> der Beginn der eigenen Arbeit, <span class="math inline">\(f\)</span> die Fertigstellung, <span class="math inline">\(D\)</span> die relative Deadline, <span class="math inline">\(d = r + D\)</span> die absolute, <span class="math inline">\(R = f - r\)</span> die Antwortzeit, Slack gleich <span class="math inline">\(d - f\)</span>. OS ist das Betriebssystem. Ein negativer Slack verletzt diese Frist und ist kein Straßenverkehrsurteil. Das Tool kennt <span class="math inline">\(d\)</span> nur, wenn wir sie konfigurieren oder aus Ereignissen rekonstruieren. Eine laufende Taskspur enthält Freigabe und Deadline nicht von selbst. Das gehaltene Beispiel der nächsten Folie hat Slack 1 ms. Eine Variante mit Fertigstellung nach <span class="math inline">\(d\)</span> hätte negativen Slack und muss als solche beschriftet sein.</p>
<p>Bei einer externen Reaktion gibt es mehrere Latenzabschnitte.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="metrik-3-interrupt-latenz" class="slide level2" data-background-color="#FFFFFF">
<h2>Metrik 3: Interrupt-Latenz</h2>
<p>Kette, nicht eine Zahl:</p>
<ol type="1">
<li>Flanke → ISR-Eintritt</li>
<li>ISR-Laufzeit</li>
<li>Veröffentlichung → Task Ready</li>
<li>Ready → Task-Start</li>
<li>Start → sichtbare Reaktion</li>
</ol>
<p>Folie zur „ersten Bottom-Half-Zeile“ meint eine <strong>Dispatchlatenz</strong> bis zu einem definierten Maschinenpunkt, nicht die IRQ-Eintrittslatenz und nicht die End-to-End-Reaktion.</p>
<p>Synthetisches Beispiel, keine Adaptermessung. Uhr hypothetisch gemeinsam.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Marke</th>
<th style="text-align: right;">Zeit</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>externe Flanke</td>
<td style="text-align: right;">100 µs</td>
</tr>
<tr class="even">
<td>ISR-Eintritt</td>
<td style="text-align: right;">106 µs</td>
</tr>
<tr class="odd">
<td>Veröffentlichung</td>
<td style="text-align: right;">110 µs</td>
</tr>
<tr class="even">
<td>Task Ready</td>
<td style="text-align: right;">111 µs</td>
</tr>
<tr class="odd">
<td>ISR-Ende</td>
<td style="text-align: right;">115 µs</td>
</tr>
<tr class="even">
<td>Task beginnt</td>
<td style="text-align: right;">120 µs</td>
</tr>
<tr class="odd">
<td>physische Reaktion</td>
<td style="text-align: right;">128 µs</td>
</tr>
</tbody>
</table>
<p>Daraus: 6 µs Eintritt, 9 µs ISR-Intervall, 9 µs Ready bis Start, 28 µs Ende zu Ende. Die Summe der disjunkten Stücke 6 + 4 + 1 + 9 + 8 ist 28. Die vollen 9 µs ISR nicht noch einmal addieren.</p>
<p>Eine Messung ist keine obere Schranke. „Erste C-Zeile“ ist bei <code>-O2</code> unscharf.</p>
<aside class="notes">
<p>IRQ ist die Anforderung, ISR die Behandlungsroutine. Bottom Half ist die aufgeschobene Arbeit, hier oft eine M4-Task. Die Kette hat mehrere Endpunkte: Flanke bis ISR-Eintritt, ISR-Dauer, Veröffentlichung bis Ready, Ready bis erster Maschinenpunkt der Task, Start bis physische Reaktion. Diese Abschnitte überlappen. Eine Veröffentlichung kann innerhalb der ISR liegen. Man addiert nicht die volle ISR-Zeit noch einmal zu allen Teilintervallen. Die gemeinsame Uhr oder die Korrelation von externer Flanke und internem Stempel muss benannt sein. „Erste C-Zeile“ ist bei <code>-O2</code> kein eindeutiger Maschinenpunkt. Welches Intervall das Zubehör sieht, bleibt offen, bis der Adapter feststeht. Eine Messung ist keine obere Schranke.</p>
<p>Das Jobbeispiel trennt eigene CPU-Arbeit von der verstrichenen Antwortzeit.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="netto-rechenzeit-vs.-brutto-antwortzeit" class="slide level2">
<h2>Netto-Rechenzeit vs.&nbsp;Brutto-Antwortzeit</h2>
<p>Lehrbeispiel, Overhead in diesem Bild <strong>0</strong>:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Marke</th>
<th style="text-align: right;">Zeit</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(r\)</span></td>
<td style="text-align: right;">1 ms</td>
</tr>
<tr class="even">
<td>Running</td>
<td style="text-align: right;">2–4 ms</td>
</tr>
<tr class="odd">
<td>Präemption</td>
<td style="text-align: right;">4–6 ms</td>
</tr>
<tr class="even">
<td>Running</td>
<td style="text-align: right;">6–7 ms</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(f\)</span></td>
<td style="text-align: right;">7 ms</td>
</tr>
<tr class="even">
<td><span class="math inline">\(d\)</span></td>
<td style="text-align: right;">8 ms</td>
</tr>
</tbody>
</table>
<p>CPU-Zeit des Jobs: 3 ms. <span class="math inline">\(R = 6\,\mathrm{ms}\)</span>. Slack: 1 ms.</p>
<p>Lehrdiagramm, Overhead 0, keine Messung. Eine Spur je Teilnehmer.</p>
<p><img data-src="../_livefigures/inline-plantuml-9a928621.svg" class="livefigure"></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Zeit</th>
<th>Task A</th>
<th>fremde Arbeit</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1–2 ms</td>
<td>wartet nach Freigabe</td>
<td>—</td>
</tr>
<tr class="even">
<td>2–4 ms</td>
<td>läuft, 2 ms</td>
<td>—</td>
</tr>
<tr class="odd">
<td>4–6 ms</td>
<td>verdrängt</td>
<td>2 ms</td>
</tr>
<tr class="even">
<td>6–7 ms</td>
<td>läuft, 1 ms</td>
<td>—</td>
</tr>
<tr class="odd">
<td>7 ms</td>
<td>fertig</td>
<td>Deadline bei 8 ms</td>
</tr>
</tbody>
</table>
<p>Das ist nicht die WCET.</p>
<aside class="notes">
<p>Die Tabelle ist ein synthetisches Modell mit Overhead null. CPU ist die eigene Rechenzeit von Task A: <span class="math inline">\((4-2)+(7-6)=3\)</span> ms. Die Antwortzeit ist <span class="math inline">\(f-r=6\)</span> ms, der Slack <span class="math inline">\(d-f=1\)</span> ms. Anfangswarten 1 ms plus Präemption 2 ms plus eigene Arbeit 3 ms ergeben dieselben 6 ms. ISR-Zeit wird A nicht zugeschlagen, wenn sie auf der Systemspur liegt. Nach <span class="math inline">\(f\)</span> kann der Thread weiterleben. Die Jobdauer ist nicht die Tasklebensdauer. Die 3 ms sind die Zeit dieses Modelljobs, keine WCET.</p>
<p>Reale Kontextwechsel brauchen Arbeit, die dieses Bild bewusst auf null setzt.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="metrik-4-context-switch-overhead" class="slide level2" data-background-color="#F5F5F7">
<h2>Metrik 4: Context Switch Overhead</h2>
<p>PendSV ist ein Teil. Dazu können Exception-Eintritt, Rückkehr, FPU, Scheduler und die Präemption selbst gehören.</p>
<p>Dieselbe Zeit nicht zweimal in die Antwortzeitanalyse zählen.</p>
<p>2,5 µs ist ein Beispiel, keine Kennzahl des H755.</p>
<aside class="notes">
<p>PendSV ist die aufschiebbare Exception, über die der FreeRTOS-Port den Kontextwechsel erledigt. Der Handlerumfang ist nicht automatisch das Intervall zwischen dem letzten Befehl von Task A und dem ersten von Task B. Register, Stack, Scheduler, Exception-Eintritt, FPU-Kontext und verschachtelte Ereignisse können dazugehören, je nach Vertrag. FPU ist die Gleitkommaeinheit. Tail-Chaining und Lazy-FPU sind optionale Vertiefungen, keine feste Dauer. Die 2,5 µs sind synthetisch und kein H755-Benchmark. Overhead entweder separat modellieren oder in den gemessenen Größen belassen, nicht doppelt addieren. Anfang und Ende müssen im Trace benannte Kanten sein.</p>
<p>Traces können außerdem Pfade für die Testabdeckung sichtbar machen.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="ausblick-code-coverage-testabdeckung" class="slide level2">
<h2>Ausblick: Code Coverage (Testabdeckung)</h2>
<p><code>if (a &amp;&amp; b)</code>, Kurzschluss: bei <code>a == false</code> wird <code>b</code> nicht ausgewertet.</p>
<table class="caption-top">
<colgroup>
<col style="width: 8%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 22%">
<col style="width: 22%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th>Test</th>
<th>Eingabe a</th>
<th>Eingabe b</th>
<th>ausgewertetes a</th>
<th>ausgewertetes b</th>
<th>Entscheidung</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>T1 TT</td>
<td>true</td>
<td>true</td>
<td>true</td>
<td>true</td>
<td>wahr</td>
</tr>
<tr class="even">
<td>T2 TF</td>
<td>true</td>
<td>false</td>
<td>true</td>
<td>false</td>
<td>falsch</td>
</tr>
<tr class="odd">
<td>T3 FT</td>
<td>false</td>
<td>true</td>
<td>false</td>
<td>nicht ausgewertet</td>
<td>falsch</td>
</tr>
</tbody>
</table>
<p>Bei <code>a == false</code> wird <code>b</code> nicht ausgewertet. Die Eingabe <code>b = true</code> im FT-Test ist kein beobachtetes Laufzeitergebnis. Unabhängigkeit im Booleschen Modell: für <code>a</code> das Paar TT/FT, für <code>b</code> das Paar TT/TF.</p>
<p>Statement Coverage zählt ausführbare Anweisungen, nicht Textzeilen. Decision ist nicht Condition. MC/DC braucht diese Paare und definierte Regeln bei Kurzschluss.</p>
<p>Instruction Trace plus Mapping ist kein automatischer MC/DC-Nachweis. Optimierung verändert das Bild. Coverage zeigt nicht, dass die Funktion richtig ist oder die Frist hält.</p>
<p>Die NASA-Notiz ist ein Tutorial im Kontext von DO-178B. Das ist keine „absolute Pflicht“ für dieses Labor.</p>
<aside class="notes">
<p>MC/DC, Modified Condition/Decision Coverage, verlangt den unabhängigen Einfluss jeder Bedingung nach einer benannten Regel. NASA, National Aeronautics and Space Administration, beschreibt das im Tutorial NASA/TM-2001-210876, Abschnitt 3.6, im historischen DO-178B-Kontext. Daraus folgt keine Laborpflicht und kein Werkzeugstempel. Statement Coverage zählt ausführbare Anweisungen. Decision Coverage die beiden Ausgänge. Condition Coverage true und false der ausgewerteten Bedingungen. Im Beispiel <code>if (a &amp;&amp; b)</code> wertet Test FT die Bedingung b nicht aus. Die Eingabe b gleich true ist der Testvertrag, kein Traceereignis. Die Paare TT/FT und TT/TF zeigen den Einfluss von a und b im Booleschen Modell. ETM-Kontrollfluss mit Quellzuordnung ist allein kein MC/DC-Nachweis.</p>
<p>Das Werkzeug muss Trace aufnehmen und dem Build zuordnen.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="das-werkzeug-in-circuit-emulator-ice" class="slide level2">
<h2>Das Werkzeug: In-Circuit Emulator (ICE)</h2>
<ul>
<li>BlueBox und winIDEA nur in der Version, die im Labor steht</li>
<li>Modell, Active Probe, Adapter und Zusatzmodule aufschreiben, bevor eine Folie sie zeichnet</li>
<li>Hier: Liste offen</li>
</ul>
<aside class="notes">
<p>ICE, In-Circuit Emulator, bezeichnet historisch ein Gerät, das den Prozessor ersetzte. Ein heutiger Debugger oder Recorder muss das nicht. Er braucht Debugadapter, gegebenenfalls eine Active Probe, Aufnahme, Puffer und Analysesoftware. Die Liste offener Geräte ist eine Konfigurationstabelle, kein Beweis, dass ein Modell im Labor steht. Herstellerseiten widersprechen sich bei Schnittstellen. Die Hardwareversion und die Anleitung gewinnen. Eine Verbindung und eine unterstützte Tracequelle sind zwei Prüfungen.</p>
<p>BlueBox ist eine Produktfamilie für solche Funktionen, kein belegtes Kursgerät.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="vorstellung-tasking-bluebox" class="slide level2" data-background-color="#FFFFFF">
<h2>Vorstellung: TASKING BlueBox</h2>
<p>Offen, bis das Gerät da ist:</p>
<ul>
<li>genaue Typbezeichnung</li>
<li>ob paralleler Trace, SWO oder nur Debug</li>
<li>Ethernet der Box, nicht raten</li>
<li>keine Gigabit-Annahme</li>
<li>keine externen ADIO-Pins ohne Modul</li>
</ul>
<aside class="notes">
<p>Die BlueBox steht im Schema als Recorderrolle. Ein bestimmtes Modell ist nicht belegt. SWO ist der serielle Traceausgang, nicht der SWD-Datenkanal. ADIO, falls das Handbuch es für das vorhandene Modul so nennt, wäre ein digitaler Erfassungsweg. Ohne Modul erfinden wir keine Portfunktion. Debugzugriff, Instruction- und Data-Trace, externe Erfassung und Hostübertragung sind getrennte Fähigkeiten. FBridge und FNet sind Anschlüsse zum Zubehör, kein austauschbares Host-Ethernet, auch wenn Stecker ähnlich aussehen. Die Konfigurationstabelle hat Spalten für Gerät, Revision, Probe, Adapter, Tracepfad und Zeitquelle. „Offen“ nennt die Prüfstelle. Der didaktische Ersatz ist der lokale Zähler oder GPIO.</p>
<p>winIDEA verbindet Recorderdaten, Maschinenbild und Auswertung, sobald eine Installation feststeht.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="die-ide-winidea" class="slide level2">
<h2>Die IDE: winIDEA</h2>
<p>Menüpfade der <strong>installierten</strong> Version. „Plugins → FreeRTOS“ nicht als ewig gültig abschreiben.</p>
<p>Geladen wird die ELF des gemessenen Builds, inklusive DWARF, für jeden Kern die eigene Datei. Hash oder Build-ID notieren.</p>
<aside class="notes">
<p>IDE, Integrated Development Environment, ist hier winIDEA als Analyseumgebung. ELF ist das Image, DWARF die Debuginformation darin. Arbeitsbereich, Ziel, Symboldatei, Recorder und Analysedarstellung sind Funktionen. Menüpfade gelten nur für eine bestätigte Version. Die online geprüfte Hilfe 9.26.20 ist nicht die Kursinstallation. Je Kern wird die ELF geladen, die zum laufenden Image passt. Hash oder Build-ID identifizieren den Build. Zwei ELF-Container können verschiedene Hashes haben, obwohl das Maschinenbild gleich ist, weil Debugmetadaten dazukommen. Ein neu gebauter Debuglauf kann andere Zeiten und Adressen haben als der optimierte Lauf. Entscheidend sind Buildzuordnung und die wirklich geladenen Bereiche.</p>
<p>Die nächste Folie trennt die Inhalte der ELF.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="elf-maschinenbild-symbole-und-debugzuordnung" class="slide level2">
<h2>ELF: Maschinenbild, Symbole und Debugzuordnung</h2>
<ul>
<li>Adressen, Typen, manchmal Zeilen</li>
<li>mehrere Befehle je Zeile, Zeilen ohne Code</li>
<li>der Decoder braucht dasselbe Image wie der Chip</li>
<li>ein anderes ELF erklärt den Trace falsch, ohne dass das Tool „lügt“</li>
</ul>
<aside class="notes">
<p>ELF trägt das Maschinenbild, Symbole und optional DWARF. DWARF, Debugging With Attributed Record Formats, liefert Typen und Zeilen. Der Kontrollflussdecoder braucht das Maschinenbild und das Protokoll. Symbole und DWARF machen daraus Funktions- und Quellnamen. Nicht jedes ELF enthält vollständige Debugdaten. Optimierung verschiebt die Zuordnung. Eine falsche Builddatei erzeugt plausible, aber falsche Namen. Fehlende Sync-Pakete machen den Abschnitt für Summen und Coverage ungültig. Das ist eine Eigenschaft der Aufnahme, nicht der ELF. Nach neuer Synchronisation kann ein späterer Abschnitt separat gelten. Die Lücke selbst bleibt unbekannt.</p>
<p>Der Profiler bestimmt danach, welchen Ausschnitt er aufzeichnet.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="der-profiler-und-trigger" class="slide level2">
<h2>Der Profiler und Trigger</h2>
<ul>
<li>Trigger brauchen freie Komparatoren und eine Route</li>
<li><code>error_flag == 1</code> ist ein Beispiel, keine eingebaute Fähigkeit jeder Box</li>
<li>„10 Sekunden alles“ hängt an Puffer und Rate</li>
<li>Für die Ursache oft ein Ring mit Pre-Trigger, nicht erst ab dem Fehler starten</li>
</ul>
<p>Synthetisches Beispiel, keine Gerätekapazität: 2 MiB bei 400 KiB/s ergeben 5,12 s vor Overhead.</p>
<div class="cell" data-reveal="true" data-fig-width="8.4" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'theme': 'base', 'themeVariables': {'background': '#FFFFFF', 'primaryColor': '#FFFFFF', 'primaryBorderColor': '#E5E5EA', 'primaryTextColor': '#1D1D1F', 'lineColor': '#86868B'}}}%%
flowchart LR
  U["Ursache im Pre-Trigger"] --&gt; TR["Trigger"]
  TR --&gt; N["begrenzter Nachlauf"]
  N --&gt; O["älterer Inhalt wird überschrieben"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<aside class="notes">
<p>Ein Trigger ist die Bedingung, die Aufnahme startet, stoppt oder nur markiert. Pre-Trigger ist die gespeicherte Historie davor, typisch in einem Ringpuffer. DWT kann eine Datenbedingung liefern, ETM den Kontrollfluss. <code>error_flag == 1</code> ist ein Beispiel. Die Umsetzung braucht Adresse, Breite und einen freien Komparator. Ein Wertvergleich kann eine weitere Ressource kosten. Die Rechnung 2 MiB bei 400 KiB/s gleich 5,12 s ist synthetisch und keine BlueBox-Kapazität. Vor der Auswertung prüfen wir Sync, passende ELF, Overflow-Hinweise und die Zeitbasis. Ein fehlender Overflow-Hinweis beweist ohne passende Quelle keine Vollständigkeit.</p>
<p>Rohereignisse brauchen danach den Betriebssystemkontext.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="das-problem-der-os-sichtbarkeit" class="slide level2">
<h2>Das Problem der OS-Sichtbarkeit</h2>
<p><code>pxCurrentTCB</code> im lokalen M4-Kernel: die <strong>ausgewählte</strong> Task.</p>
<p>Während der ISR zeigt der Zeiger oft weiter auf sie, obwohl kein Taskcode läuft.</p>
<p>Der Wechsel liegt im Context Switch und ist nicht zwingend der erste Zyklus der neuen Task.</p>
<p>Ein wiederverwendeter TCB-Pointer ist keine ewige ID. Layout der eingesetzten Kernelversion prüfen. SMP-Strukturen sind hier nicht der M4-Kernel.</p>
<aside class="notes">
<p>OS ist das Betriebssystem, TCB der Task Control Block. <code>pxCurrentTCB</code> gehört zum Single-Core-M4-Kernel und zeigt auf den ausgewählten Taskblock. Während ISR oder PendSV kann der Zeiger weiter auf eine Task zeigen, obwohl der Kern deren Code nicht ausführt. Der Wechsel des Zeigers ist nicht automatisch der erste Taskbefehl. Der Port und der Decoder müssen die Grenze liefern. Wiederverwendete Adressen brauchen eine Lebensdauer. SMP-Strukturen erklären diesen M4-Kern nicht. Ein Running-Profil ist die Ausführungshistorie, nicht die Ready- und Blocked-Historie.</p>
<p>OS-Awareness kombiniert mehrere Informationen und hat Ausbaustufen.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="os-awareness-betriebssystem-bewusstsein" class="slide level2" data-background-color="#FFFFFF">
<h2>OS-Awareness (Betriebssystem-Bewusstsein)</h2>
<p>Zwei Stufen:</p>
<ol type="1">
<li>Running: aus <code>pxCurrentTCB</code> und dem Trace, ISR und PendSV daneben</li>
<li>Zustände Ready/Blocked: zusätzliche Instrumentierung, Aufwand kennzeichnen</li>
</ol>
<p>Debug-Listen sind keine lückenlose Live-Historie.</p>
<p>ORTI/OSEK bleibt etwas anderes als FreeRTOS-Awareness. Queues können extra Registrierung brauchen.</p>
<aside class="notes">
<p>Drei Darstellungen bleiben getrennt. Die Debuggerliste zeigt aktuelle Kernelobjekte. Das Running-Profil zeigt, welche Task oder ISR in gültigen Ereignissen lief. Ein Zustandstrace mit Ready und Blocked braucht zusätzliche Instrumentierung. Ready heißt ausführungsbereit, Blocked heißt Warten, Running heißt tatsächliche Ausführung unter der gewählten Zuordnung. Der Taskzeiger allein liefert nicht alle drei. Während einer ISR zeigt er oft die zuletzt ausgewählte Task, nicht „die ISR ist diese Task“. ORTI, OSEK Run Time Interface, ist ein anderer Beschreibungsstandard und kein FreeRTOS-Plugin. Kernelversion und registrierte Queues werden geprüft.</p>
<p>Ein Lehrschema zeigt das, ohne einen Laborscreenshot vorzutäuschen.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="wie-winidea-freertos-visualisiert" class="slide level2">
<h2>Wie winIDEA FreeRTOS visualisiert</h2>
<p>Lehrschema, keine Laboraufnahme. Menüs gelten nur für die installierte Hilfe.</p>
<p><img data-src="../_livefigures/inline-plantuml-4c75f570.svg" class="livefigure"></p>
<p>Beide Kernspuren gleichzeitig nur, wenn beide Quellen wirklich korreliert aufgenommen werden. Sonst zwei Aufnahmen und keine Subtraktion der Zeitachsen.</p>
<aside class="notes">
<p>Das Bild ist ein Lehrschema, keine Laboraufnahme. Task A, Task B, ISR und PendSV haben eigene Spuren. Ready und Blocked erscheinen nur, wenn sie instrumentiert sind. Ein Running-Profil wird nicht stillschweigend zur Zustandshistorie. RTOS ist das Echtzeitbetriebssystem auf dem M4. Zwei Kernspuren auf einer Achse brauchen gleichzeitige Aufnahme und Korrelation. Sonst bleiben getrennte Achsen. Unabhängige Zykluszähler werden nicht voneinander abgezogen. Fehlende Screenshots ersetzen wir durch dieses Schema, nicht durch ein nachgemaltes Fenster.</p>
<p>Ein anderer Standard beschreibt OS-Objekte im Automotive-Kontext.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="der-osekorti-standard-automotive" class="slide level2">
<h2>Der OSEK/ORTI-Standard (Automotive)</h2>
<ul>
<li>ORTI beschreibt OSEK/AUTOSAR-OS-Objekte</li>
<li>FreeRTOS-Awareness ist ein anderes Plugin und ein anderes Layout</li>
<li>Beides nicht vermischen, auch wenn beide „Tasks“ zeichnen</li>
</ul>
<aside class="notes">
<p>OSEK steht für offene Systeme und deren Schnittstellen in der Automobilelektronik. ORTI beschreibt Lage und Bedeutung von Betriebssystemobjekten für Werkzeuge. Diese Metadaten erzeugen keine Ereignishistorie. AUTOSAR, AUTomotive Open System ARchitecture, nutzt eigene OS-Schnittstellen. Eine ähnliche Taskliste ist nicht dieselbe Schnittstelle. Einen neueren Standard wie ARTI nennen wir nur als Ausblick, ohne ihn als Laborpflicht zu setzen. Für dieses Labor zählt die lokale M4-FreeRTOS-Instanz, nicht ein AUTOSAR-OS.</p>
<p>Die Konzepte werden nun in Messversuchen angewendet.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="laborvorbereitung-tracing-im-einsatz" class="slide level2" data-background-color="#F5F5F7">
<h2>Laborvorbereitung: Tracing im Einsatz</h2>
<p>Ohne Spezialhardware: GPIO um die Funktion oder <code>CYCCNT</code> desselben Kerns. Lehrumrechnung, keine Boardmessung: bei 400 MHz sind 1000 Takte 2,5 µs, bei 200 MHz 5 µs. Den Zähler des anderen Kerns nicht subtrahieren.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode numberSource c number-lines code-with-copy"><code class="sourceCode c"><span id="cb1-1"><a aria-label="1"></a><span class="co">/* Ungebautes Lehrbeispiel. CYCCNT nur, wenn der Kern ihn hat. */</span></span>
<span id="cb1-2"><a aria-label="2"></a><span class="dt">uint32_t</span> before <span class="op">=</span> DWT<span class="op">-&gt;</span>CYCCNT<span class="op">;</span></span>
<span id="cb1-3"><a aria-label="3"></a><span class="dt">uint32_t</span> result <span class="op">=</span> work_under_test<span class="op">();</span></span>
<span id="cb1-4"><a aria-label="4"></a><span class="dt">uint32_t</span> after <span class="op">=</span> DWT<span class="op">-&gt;</span>CYCCNT<span class="op">;</span></span>
<span id="cb1-5"><a aria-label="5"></a><span class="dt">uint32_t</span> delta <span class="op">=</span> after <span class="op">-</span> before<span class="op">;</span> <span class="co">/* kurz, kürzer als ein Umlauf */</span></span>
<span id="cb1-6"><a aria-label="6"></a><span class="op">(</span><span class="dt">void</span><span class="op">)</span>result<span class="op">;</span> <span class="co">/* Ergebnis benutzen, damit der Compiler work nicht streicht */</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><code>work_under_test</code> ist eine benannte Funktion mit verwendetem Ergebnis, keine leere Hülle. Die Differenz enthält Unterbrechungen, solange der Zähler läuft. Reine Task-CPU-Zeit braucht eine Running-Zuordnung. Kein <code>printf</code> zwischen den beiden Lesungen.</p>
<p>Versuch A: eine <code>uint32_t</code>-Variable mit alleinigem Schreiber, Werte 0, 1, 2 nach dokumentierter Init. Ein fehlendes Anfangspaket ist nicht der Wert 0.</p>
<p>Versuch B: non-cacheable Ping-Pong aus VL6. Druck 1, 3, 5. Die 500 ms liegen außerhalb der IPC-Messung.</p>
<p>Versuch C: separates Image, D-Cache an, Region nachweislich Write-Back. Hypothese, kein Drehbuch: M7-Store 1 kann da sein, M4 liest weiter 0. Kein garantierter Freeze. Timeout und Abbruch wie in VL6.</p>
<p>Versuch D: ein Job mit definierten Kanten. Min, Max, Anzahl, Auflösung, Bedingungen. Verluste machen die Summe ungültig.</p>
<aside class="notes">
<p>Der Basisteil braucht keinen Recorder. CYCCNT ist der lokale DWT-Zykluszähler des gewählten Kerns, keine zweite Systemuhr. Zwei <code>uint32_t</code>-Stände, <code>after - before</code>, gelten im Modell, solange das Intervall kürzer als eine Zählerperiode ist. Bei den Lehrfrequenzen 400 MHz und 200 MHz sind 1000 Takte 2,5 µs beziehungsweise 5 µs. Die 32-Bit-Periode liegt dann bei etwa 10,74 s beziehungsweise 21,47 s. Das sind keine bestätigten Boardtakte. Der Zähler umfasst Interrupts, wenn er weiterläuft. <code>printf</code> steht nicht zwischen den Lesungen. Das Ergebnis wird lokal gehalten. Der Code ist ungebaut, bis die CMSIS-Header des Ziels die Register bestätigen.</p>
<p>Versuch A vergleicht einen bekannten Anfang mit einem fehlenden ersten Paket. Ein Default 0 ist keine Beobachtung. Versuch B nutzt den nicht cachebaren Ping-Pong aus Vorlesung 6. Der M7-Roundtrip misst mit einer Uhr um Veröffentlichung und Antwort. Die 500-ms-Pause liegt außerhalb. Getrennte M7- und M4-Aufnahmen ergeben ohne Korrelation keine Inter-Core-Latenz. Versuch C ist ein separater Write-Back-Build, kein korrektes IPC. Versuch D berechnet CPU-Zeit, Antwortzeit und Slack nur über vollständige Jobkanten.</p>
<p>Das M4-Profil wird mit klarer Informationsgrenze eingerichtet.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="lehrversuche-a-bis-d-zu-folie-labor" class="slide level2">
<h2>Lehrversuche A bis D, zu Folie Labor</h2>
<p>Jeder Kasten ist ein Vertrag. Erwartete Werte sind Lehrannahmen, keine Targetmessung. Abbruch: Timeout wie in Vorlesung 6, Shared-Block nicht neu initialisieren, solange die Gegenstelle läuft.</p>
<table class="caption-top">
<colgroup>
<col style="width: 9%">
<col style="width: 29%">
<col style="width: 20%">
<col style="width: 23%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th>Feld</th>
<th>A lokale Variable</th>
<th>B Ping-Pong</th>
<th>C Cachefehler</th>
<th>D ein Job</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Frage</td>
<td>fehlt der Anfang?</td>
<td>Roundtrip einer Uhr</td>
<td>sieht M4 den Store?</td>
<td>CPU, Antwort, Slack</td>
</tr>
<tr class="even">
<td>Kern</td>
<td>ein Kern, alleiniger Schreiber</td>
<td>M7 misst, M4 antwortet</td>
<td>separates M7-Image</td>
<td>M4-Task</td>
</tr>
<tr class="odd">
<td>Anfang/Ende</td>
<td>vor erstem Schreiben und nach 0, 1, 2</td>
<td>um Veröffentlichung und Antwort</td>
<td>Store und benannter M4-Leseweg</td>
<td>Freigabe bis Jobende, Running-Abschnitte</td>
</tr>
<tr class="even">
<td>Quelle</td>
<td>DWT oder synthetische Tabelle</td>
<td>Marker oder CYCCNT des M7</td>
<td>DWT-Store und M4-Beobachtung</td>
<td>Kernelereignis oder CYCCNT/GPIO</td>
</tr>
<tr class="odd">
<td>Uhr</td>
<td>lokale Zählung, Frequenz prüfen</td>
<td>dieselbe M7-Uhr</td>
<td>nicht zwei CYCCNT subtrahieren</td>
<td>eine benannte Uhr</td>
</tr>
<tr class="even">
<td>Enthalten</td>
<td>nur diese Schreibfolge</td>
<td>M4-Arbeit, Poll, Rückgabe</td>
<td>kein Logging im Fenster</td>
<td>Interrupts nur, wenn die Definition sie einschließt</td>
</tr>
<tr class="odd">
<td>Abbruch</td>
<td>kein Paket als 0 lesen</td>
<td>500 ms Pause außerhalb</td>
<td>Cachewartung aus</td>
<td>Lücken aus der Summe</td>
</tr>
</tbody>
</table>
<p>Versuch A ohne DWT: eine synthetische Ereignistabelle zeigt „kein Paket“ und „Paket 0“ als zwei Zeilen. Versuch B behält <code>ipc.magic</code>, <code>ipc.state</code>, <code>ipc.payload</code> und die nicht cachebare MPU-Basis. Druck 1, 3, 5 ist das Protokoll. Versuch C prüft CCR, Shareability und Überlappung. Weiterhin shareable kann die Cachewirkung verhindern. Versuch D nennt Min, beobachtetes Max, Anzahl, Einheit, Auflösung und die Zahl ausgeschlossener Jobs. Das Maximum ist keine WCET.</p>
<aside class="notes">
<p>Die vier Verträge gehören zur Laborfolie. A trennt einen aufgenommenen Wert 0 von einem fehlenden Anfang. B ist der nicht cachebare Kanal aus Vorlesung 6. Der M7-Roundtrip enthält Bearbeitung, Polling und Rückgabe und ist keine isolierte Einweglatenz. C ist ein Fehlerexperiment in einem eigenen Build. Ein ausbleibender Fehler beweist die Korrektheit nicht. D rechnet eigene CPU-Zeit, Antwortzeit und Slack nur über vollständige Kanten. Ein CYCCNT- oder GPIO-Intervall um eine präemptierbare Funktion heißt Intervall, nicht reine Taskzeit.</p>
<p>Danach wird das M4-Running-Profil mit eigener Spur für ISR und PendSV eingerichtet.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="schritt-34-freertos-awareness-profiler" class="slide level2">
<h2>Schritt 3–4: FreeRTOS Awareness &amp; Profiler</h2>
<p>Running-Profil der M4-Task: wiederkehrendes Delay ist Blocked/Ready/Running im Polling, kein eingefrorener Kern.</p>
<p><code>osDelay(1)</code> ist ein Tick. Die Poll-Latenz ist nicht nur die Umschaltzeit.</p>
<p>Zustandshistorie nur mit der zusätzlichen Konfiguration und als instrumentierte Variante beschriftet.</p>
<aside class="notes">
<p>Der Ablauf ist: Build zuordnen, Beobachtungspfad bestätigen, Trace konfigurieren, Running-Profil einrichten, Zustandstrace nur optional. RTOS ist FreeRTOS auf dem M4. <code>osDelay(1)</code> blockiert für mindestens einen Kernel-Tick. Die Dauer des Ticks steht im Ziel, nicht in dieser Folie. Die Task wird blockiert und später bereit. Ein Running-Profil belegt nicht jede interne Zustandskante. ISR und PendSV bekommen eigene Spuren. Ihre Zeit wird der Task nicht als eigene CPU-Zeit zugeschlagen. Eine Pollreaktion enthält Pollintervall, Ready-Wartezeit und Bearbeitung, nicht nur den Kontextwechsel. TCB ist der Taskblock, dessen Zeiger während der ISR stehen bleiben kann.</p>
<p>Erst nach der Qualitätsprüfung beginnt die Auswertung.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="schritt-5-die-aufnahme-analyse" class="slide level2">
<h2>Schritt 5: Die Aufnahme &amp; Analyse</h2>
<p>Diagnose, je eine Prüfung:</p>
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Symptom</th>
<th>Prüfung</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>keine Verbindung</td>
<td>Versorgung, Reset-Reihenfolge, richtiger Adapter</td>
</tr>
<tr class="even">
<td>nur ein Kern</td>
<td>ELF und Core-Zuordnung</td>
</tr>
<tr class="odd">
<td>keine Datenpakete</td>
<td>Komparator, Adresse, Breite, Startzeit</td>
</tr>
<tr class="even">
<td>falsche Achse</td>
<td>Zeitquelle, nicht nur 400 MHz</td>
</tr>
<tr class="odd">
<td>Anfang fehlt</td>
<td>nicht als 0 werten</td>
</tr>
<tr class="even">
<td>Verluste</td>
<td>Lücke markieren; Summen nur über vollständige Abschnitte. Nach neuer Sync kann ein späterer Abschnitt separat gelten</td>
</tr>
<tr class="odd">
<td>falsche Tasks</td>
<td>Kernelversion, TCB-Layout</td>
</tr>
<tr class="even">
<td>nur Running</td>
<td>State-Profiling fehlt</td>
</tr>
<tr class="odd">
<td>Cachefehler bleibt aus</td>
<td>CCR, MPU, Neustart, Debug-Cachewartung aus</td>
</tr>
</tbody>
</table>
<aside class="notes">
<p>Die Tabelle ist eine Folge von Hypothesen, keine feste Zuordnung Symptom gleich Ursache. Zuerst Aufbau, Kern, Build und Zeitquelle, dann Filter und Datenqualität, zuletzt die abgeleiteten Größen. ELF muss zum laufenden Image passen. Ein fehlender Anfangswert bleibt unbekannt und wird nicht als 0 gelesen. Verlustintervalle werden markiert. Summen laufen nur über vollständige Abschnitte. Nach neuer Synchronisation und bekannter Kontextzuordnung kann ein späterer Abschnitt separat gelten. CCR und MPU entscheiden im Cacheversuch, ob die Region wirklich Write-Back ist. Live-Memory und automatische Cachewartung können Versuch C verfälschen. Sie bleiben aus oder werden als Störung protokolliert. TCB-Wechsel während einer ISR ist keine Taskausführung.</p>
<p>Die Schlussfolie fasst Messdefinition und zulässige Aussage zusammen.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="zusammenfassung-des-tages" class="slide level2" data-background-color="#FFFFFF">
<h2>Zusammenfassung des Tages</h2>
<ul>
<li>Messfrage, Quelle, Grenze</li>
<li>434 µs Leitungszeit, 3 ms CPU, 6 ms Antwort, 1 ms Slack im Lehrjob</li>
<li>DWT am CPU-Zugriff, nicht als SRAM-Monitor</li>
<li>ETM rekonstruiert Pfade, solange das Bild vollständig ist</li>
<li><span class="math inline">\(\max(C)\)</span> ist kein WCET-Beweis</li>
<li>Hardwareliste und gleichzeitige Dual-Core-Traces bleiben offen</li>
</ul>
<aside class="notes">
<p>Eine zulässige Aussage nennt Messfrage, Quelle, Zeitbasis, Datenqualität und Grenze. Die 434 µs sind die UART-Leitungsdauer von fünf Bytes bei 8N1 und 115200 bit/s, nicht die CPU-Zeit von <code>printf</code>. Im Lehrjob sind 3 ms eigene CPU-Zeit, 6 ms Antwortzeit und 1 ms Slack. Ein DWT-Schreibereignis ist kein SRAM-Inhalt und keine M4-Sicht. ETM-Kontrollfluss gilt nur in synchronen Abschnitten. Ein Stichprobenmaximum ist keine WCET. Zwei CYCCNT-Werte verschiedener Kerne werden nicht subtrahiert.</p>
<p>Frage: Warum ist das größte Messergebnis kein Beweis? Weil andere Pfade länger sein können. Frage: Wann darf man nach einem Verlust wieder rechnen? Wenn Sync, Kontext und Zeitbasis für einen neuen Abschnitt stehen. Die Lücke bleibt draußen.</p>
<p>Der nächste Termin behandelt die Hardware-Semaphore zwischen den Kernen. Die Quellenliste und die offene Gerätekonfiguration stehen im Anhang, nicht als Folienbehauptung. Geprüft am 7. Oktober 2026: Cortex-M7 TRM, CMSIS-ITM-Beschreibung, UM2408 Rev.&nbsp;6, RM0399 und H755-Dokumentation, winIDEA-Hilfe 9.26.20 als Online-Stand, NASA/TM-2001-210876, FAA AC 20-115D. Die Kursinstallation und das Tracezubehör bleiben offen.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="anhang-offene-konfiguration-zu-folie-40" class="slide level2">
<h2>Anhang: offene Konfiguration, zu Folie 40</h2>
<p>Keine Laborbehauptung. Spalten: Lehrannahme, im Kursaufbau zu prüfen, Prüfstelle.</p>
<table class="caption-top">
<colgroup>
<col style="width: 16%">
<col style="width: 30%">
<col style="width: 25%">
<col style="width: 27%">
</colgroup>
<thead>
<tr class="header">
<th>Punkt</th>
<th>Lehrannahme</th>
<th>zu prüfen</th>
<th>Prüfstelle</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Bauteil</td>
<td>STM32H755, Nucleo aus VL6</td>
<td>Boardrevision</td>
<td>Aufdruck, UM2408</td>
</tr>
<tr class="even">
<td>Firmware</td>
<td>M7 Bare Metal, M4 FreeRTOS</td>
<td>ELF je Kern, Optimierung</td>
<td>Build, Map</td>
</tr>
<tr class="odd">
<td>Takt</td>
<td>400 und 200 MHz nur als Rechnung</td>
<td>Clock-Tree</td>
<td>Cube-Clock, Register</td>
</tr>
<tr class="even">
<td>CYCCNT</td>
<td>Zähler des einen Kerns</td>
<td>Freigabe, Halt, Sleep</td>
<td>TRM, CMSIS-Header</td>
</tr>
<tr class="odd">
<td>Tracepfad</td>
<td>Konzept ITM, DWT, ETM</td>
<td>Pin, Adapter, Recorder</td>
<td>Schaltplan, Gerät</td>
</tr>
<tr class="even">
<td>BlueBox, winIDEA</td>
<td>Rollen, keine Modelle</td>
<td>Version 9.26.20 ist nur online</td>
<td>Installation</td>
</tr>
<tr class="odd">
<td>Zeitkorrelation</td>
<td>eine Uhr je Messung</td>
<td>zwei Kerne gemeinsam</td>
<td>Aufnahmeprotokoll</td>
</tr>
</tbody>
</table>
<p>Selbstkontrolle, kurz: 434 µs sind Leitungszeit. Ein Breakpoint kann einen Race verschieben. Viele IRQ-Flanken im Halt erzeugen nicht viele Stackframes. <code>ITM_SendChar</code> kann warten. Ein DWT-Store 1 ist kein M4-SRAM. Ein fehlendes Paket ist nicht 0. Der ETM-Decoder braucht dasselbe Maschinenbild. Zwei CYCCNT verschiedener Kerne sind nicht eine Differenz. Der Lehrjob hat 3 ms eigene CPU-Zeit und 6 ms Antwortzeit. Decision Coverage ersetzt Condition Coverage nicht, weil im FT-Test b nicht ausgewertet wird. Nach einem Verlust gilt erst der neu synchronisierte Abschnitt.</p>
<aside class="notes">
<p>Dieser Anhang gehört zur Schlussfolie und ist kein zusätzlicher Stoff. Die Tabelle hält fest, was die Vorlesung annimmt und was am Gerät noch fehlt. Eine Lehrannahme ist keine Messung der Kategorie C. Die Selbstkontrolle wiederholt die Grenzen: Leitung gegen CPU-Zeit, Halt gegen Pending, Stimulus gegen den ganzen ITM-Baustein, Store gegen Sichtbarkeit, Stichprobe gegen WCET, Zeiger gegen Ausführung, Kurzschluss gegen beobachtetes b.</p>
<p>Damit endet der Termin. Die Hardware-Semaphore folgt als eigener Synchronisationsbaustein.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>


</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="../assets/dhbw_logo.svg" class="slide-logo"></p>
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': true,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1280,

        height: 720,

        // Factor of the display size that should remain empty around the content
        margin: 8.0e-2,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script>
    /**
     * Fit Quarto/Reveal Mermaid SVGs to remaining slide space.
     * Dimensions from getBoundingClientRect are viewport pixels; CSS sizes inside
     * Reveal slides are unscaled — divide by Reveal.getScale().
     */
    (function () {
      const BOTTOM_PAD = 36;
      const SIDE_PAD_RATIO = 0.92;
      const MAX_SCALE = 3.4;

      function presentSlide() {
        var present = document.querySelector("section.present");
        if (!present) return null;
        var nested = present.querySelector(":scope > section.present");
        return nested || present;
      }

      function revealScale() {
        if (window.Reveal && typeof Reveal.getScale === "function") {
          var s = Reveal.getScale();
          return s > 0.05 ? s : 1;
        }
        return 1;
      }

      function ensureWrap(svg) {
        var parent = svg.parentElement;
        if (!parent) return null;
        if (parent.classList.contains("mermaid-fit")) return parent;
        var wrap = document.createElement("div");
        wrap.className = "mermaid-fit";
        parent.insertBefore(wrap, svg);
        wrap.appendChild(svg);
        return wrap;
      }

      function contentBottomAbove(slide, wrap) {
        var top = slide.getBoundingClientRect().top;
        var bottom = top + 8;
        var children = slide.children;
        for (var i = 0; i < children.length; i++) {
          var el = children[i];
          if (el === wrap || el.classList.contains("mermaid-fit")) break;
          if (el.querySelector && el.querySelector("svg.mermaid-js")) break;
          if (el.tagName === "ASIDE") continue;
          var r = el.getBoundingClientRect();
          if (r.height > 1) bottom = Math.max(bottom, r.bottom);
        }
        return bottom;
      }

      function naturalSize(svg) {
        if (svg.dataset.natW && svg.dataset.natH) {
          return { w: +svg.dataset.natW, h: +svg.dataset.natH };
        }
        var vb = svg.viewBox && svg.viewBox.baseVal;
        if (vb && vb.width > 0 && vb.height > 0) {
          svg.dataset.natW = String(vb.width);
          svg.dataset.natH = String(vb.height);
          return { w: vb.width, h: vb.height };
        }
        var wAttr = parseFloat(svg.getAttribute("width"));
        var hAttr = parseFloat(svg.getAttribute("height"));
        if (wAttr > 0 && hAttr > 0) {
          svg.dataset.natW = String(wAttr);
          svg.dataset.natH = String(hAttr);
          return { w: wAttr, h: hAttr };
        }
        var r = svg.getBoundingClientRect();
        var rs = revealScale();
        var w = r.width / rs || 320;
        var h = r.height / rs || 120;
        svg.dataset.natW = String(w);
        svg.dataset.natH = String(h);
        return { w: w, h: h };
      }

      function fitMermaids() {
        var slide = presentSlide();
        if (!slide) return;

        var rs = revealScale();
        var slideRect = slide.getBoundingClientRect();
        var svgs = slide.querySelectorAll("svg.mermaid-js");

        for (var i = 0; i < svgs.length; i++) {
          var svg = svgs[i];
          var wrap = ensureWrap(svg);
          if (!wrap) continue;

          svg.style.removeProperty("transform");
          svg.style.removeProperty("max-width");
          svg.style.removeProperty("zoom");
          wrap.style.zoom = "";

          var nat = naturalSize(svg);
          var above = contentBottomAbove(slide, wrap);
          var availW = (slideRect.width * SIDE_PAD_RATIO) / rs;
          var availH = Math.max(72, (slideRect.bottom - above - BOTTOM_PAD) / rs);

          var scale = Math.min(availW / nat.w, availH / nat.h, MAX_SCALE);
          if (!(scale > 0)) scale = 1;

          var targetW = Math.max(1, Math.round(nat.w * scale));
          var targetH = Math.max(1, Math.round(nat.h * scale));

          svg.setAttribute("width", targetW);
          svg.setAttribute("height", targetH);
          svg.style.width = targetW + "px";
          svg.style.height = targetH + "px";
          svg.style.display = "block";
          svg.style.margin = "0.35rem auto 0";
        }
      }

      function scheduleFit() {
        requestAnimationFrame(function () {
          fitMermaids();
          setTimeout(fitMermaids, 150);
          setTimeout(fitMermaids, 500);
          setTimeout(fitMermaids, 1100);
        });
      }

      window.addEventListener("load", scheduleFit);

      function bindReveal() {
        if (!window.Reveal || !Reveal.on) return false;
        Reveal.on("ready", scheduleFit);
        Reveal.on("slidechanged", scheduleFit);
        if (Reveal.isReady && Reveal.isReady()) scheduleFit();
        return true;
      }

      if (!bindReveal()) {
        window.addEventListener("load", function () {
          var tries = 0;
          var id = setInterval(function () {
            if (bindReveal() || ++tries > 50) clearInterval(id);
          }, 100);
        });
      }

      window.dhbwMermaidFit = fitMermaids;
    })();
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp("https:\/\/dantschi\.github\.io\/echtzeitsysteme\/");
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>